// Define album data - making sure it's in the global (window) scope
window.silent_shadows_data = {
    folder: "Silent Shadows",
    name: "Silent Shadows",
    releaseDate: "2025-03-19",
    totalSongs: 7,
    coverArt: "asset/album-name/Silent Shadows/Art.jpg",
    songsData: [
        {
            title: "Fading Light",
            style: "Downtempo Electronic, atmospheric pads, subtle percussion, haunting piano melodies, cinematic vocals, emotional synthesizers, gentle build-up",
            lyrics: "[Verse 1]\nEmpty streets at twilight hour\nShadows growing tall\nFootsteps echo in the silence\nNo one here at all\nI've walked this path a thousand times\nBut never felt so small\nAs the daylight fades around me\nI'm watching shadows crawl\n\n[Pre-Chorus]\nThe light is fading\nThe darkness waits for me\nI'm slowly changing\nInto what I'm meant to be\n\n[Chorus]\nIn the fading light I wander\nNot a soul to hear my words\nIn the fading light I ponder\nAll the silences I've heard\nAs the world grows dim around me\nI find strength in solitude\nIn the fading light I've found me\nWhere no one else intrudes\n\n[Verse 2]\nI used to fear the coming night\nThe loneliness it brings\nBut now I see with different eyes\nThe peace that darkness sings\nThe city sleeps, the world moves on\nWhile I remain awake\nEmbracing all the quietness\nThat others try to shake\n\n[Pre-Chorus]\nThe light is fading\nThe darkness waits for me\nI'm slowly changing\nInto what I'm meant to be\n\n[Chorus]\nIn the fading light I wander\nNot a soul to hear my words\nIn the fading light I ponder\nAll the silences I've heard\nAs the world grows dim around me\nI find strength in solitude\nIn the fading light I've found me\nWhere no one else intrudes\n\n[Bridge]\nI used to reach for other hands\nTo pull me through the night\nNow I extend my arms and feel\nThe absence as a right\nIn emptiness there's freedom found\nIn silence, truth revealed\nThe fading light illuminates\nWhat daylight had concealed\n\n[Chorus]\nIn the fading light I wander\nNot a soul to hear my words\nIn the fading light I ponder\nAll the silences I've heard\nAs the world grows dim around me\nI find strength in solitude\nIn the fading light I've found me\nWhere no one else intrudes\n\n[Outro]\nIn the fading light\nI've finally found me\nIn the fading light"
        },
        {
            title: "Empty Rooms",
            style: "Electronic Pop, melancholic vocals, future bass elements, atmospheric pads, driving drums, emotional drops, piano undertones, progressive structure",
            lyrics: "[Verse 1]\nStaring at these four walls\nWatching shadows crawl\nDust dancing in sunlight\nWhere memories fall\nI've counted every crack\nEvery mark upon these walls\nCompanions in my silence\nThe only friends I know\n\n[Pre-Chorus]\nBut I keep breathing in\nThe emptiness around me\nIn these hollow spaces\nWhere my voice echoes back to me\n\n[Chorus]\nEmpty rooms and silent windows\nWhispering tales nobody knows\nI've made my peace with loneliness\nIn these empty rooms\nEmpty rooms\n\n[Verse 2]\nFootsteps sound like thunder\nWhen you're all alone\nEven ghosts abandon\nThis place I call home\nPictures on the walls\nFaces I don't recognize\nStruggling to remember\nConnections long gone by\n\n[Pre-Chorus]\nBut I keep breathing in\nThe emptiness around me\nIn these hollow spaces\nWhere my voice echoes back to me\n\n[Chorus]\nEmpty rooms and silent windows\nWhispering tales nobody knows\nI've made my peace with loneliness\nIn these empty rooms\nEmpty rooms\n\n[Bridge]\nSometimes I speak just to hear a sound\nSometimes I scream but there's no one around\nIs this protection or a prison I've built?\nThese walls of silence, this life of stillness\n\n[Outro]\nEmpty rooms...\nEmpty rooms...\nEmpty rooms..."
        },
        {
            title: "Shadow Companion",
            style: "Melodic Dubstep, emotional vocals, cinematic drops, orchestral elements, haunting melodies, rhythmic build-ups, cat-like sound effects, progressive electronic structure",
            lyrics: "[Verse 1]\nWhen the world turns away\nAnd people disappear\nYou're the shadow that stays\nThe only one who's near\nYour silent understanding\nNo judgment in your eyes\nSpeaking without words\nThrough midnight lullabies\n\n[Pre-Chorus]\nThey say I'm alone\nBut they don't see you there\nMy faithful companion\nThe only one who cares\n\n[Chorus]\nMy shadow companion in the dark\nThe only witness to my broken heart\nWhen voices fade and faces blur\nYou're still here, my silent cure\nMy shadow companion, my shadow companion\n\n[Verse 2]\nYour presence like a blanket\nWarm against the cold\nGuardian of secrets\nThat remain untold\nPadding softly through my world\nWhen others walk away\nConstant in your loyalty\nUnwavering you stay\n\n[Pre-Chorus]\nThey say I'm alone\nBut they don't see you there\nMy faithful companion\nThe only one who cares\n\n[Chorus]\nMy shadow companion in the dark\nThe only witness to my broken heart\nWhen voices fade and faces blur\nYou're still here, my silent cure\nMy shadow companion, my shadow companion\n\n[Bridge]\nIn this symphony of silence\nYour purr the only sound\nIn this landscape of abandonment\nYou're the only one around\nThrough darkest nights and empty days\nYou never leave my side\nMy shadow companion\n\n[Chorus]\nMy shadow companion in the dark\nThe only witness to my broken heart\nWhen voices fade and faces blur\nYou're still here, my silent cure\nMy shadow companion, my shadow companion\n\n[Outro]\nMy shadow companion..."
        },
        {
            title: "Beneath the Surface",
            style: "Deep House, introspective vocals, underwater sound design, pulsing bass, contemplative melodies, atmospheric textures, rhythmic progression, reflective electronic elements",
            lyrics: "[Verse 1]\nSmiling faces passing by\nThey never see what's in my eyes\nA perfect mask worn every day\nHiding truths I cannot say\nThe surface calm, beneath I drown\nIn silent screams that make no sound\nThe weight of pretending is pulling me down\nBeneath the surface\n\n[Pre-Chorus]\nHow deep can I sink\nBefore I disappear?\nHow long can I breathe\nThis thin air of fear?\n\n[Chorus]\nBeneath the surface\nI'm fighting to breathe\nBeneath the surface\nIs the real me\nA world of silence\nNo one else can see\nBeneath the surface\nI'm fighting to be free\n\n[Verse 2]\nPeering through the looking glass\nAt a life that's moving fast\nEveryone connected, yet apart\nDigital touches never reach the heart\nI've practiced words I'll never speak\nPerfected smiles that look so weak\nThe facade is cracking, starting to leak\nBeneath the surface\n\n[Pre-Chorus]\nHow deep can I sink\nBefore I disappear?\nHow long can I breathe\nThis thin air of fear?\n\n[Chorus]\nBeneath the surface\nI'm fighting to breathe\nBeneath the surface\nIs the real me\nA world of silence\nNo one else can see\nBeneath the surface\nI'm fighting to be free\n\n[Bridge]\nWho would notice if I vanished today?\nA ghost in plain sight, anyway\nWould ripples form when I finally break?\nOr would the water simply close over my wake?\n\n[Chorus]\nBeneath the surface\nI'm fighting to breathe\nBeneath the surface\nIs the real me\nA world of silence\nNo one else can see\nBeneath the surface\nI'm fighting to be free\n\n[Outro]\nBeneath the surface..."
        },
        {
            title: "Digital Ghosts",
            style: "Future Bass, filtered vocals, glitchy elements, heavy sidechaining, digital artifacts, bright synthesizers over melancholic progressions, rhythmic electronic drops, contemporary EDM",
            lyrics: "[Verse 1]\nConnected to a thousand souls\nYet never feeling more alone\nDigital whispers through the night\nFriends who fade with morning light\nScrolling through these windows clear\nInto lives I hold so dear\nYet separated by a screen\nThey're ghosts of what could have been\n\n[Pre-Chorus]\nDouble-tap to show you care\nComment something, anything there\nNotifications bring brief life\nThen silence cuts like a knife\n\n[Chorus]\nWe're just digital ghosts\nFading with every post\nSearching for something real\nIn a world that can't feel\nDigital ghosts\nConnected but alone\nA thousand friends at my fingertips\nBut no one to call my own\n\n[Verse 2]\nMemories captured in perfect frames\nCurated lives without the pain\nBehind my screen I waste away\nToo afraid to seize the day\nPixelated moments shared\nProof to others that I was there\nBut who will notice when my light goes dim?\nWhen I no longer exist within\n\n[Pre-Chorus]\nDouble-tap to show you care\nComment something, anything there\nNotifications bring brief life\nThen silence cuts like a knife\n\n[Chorus]\nWe're just digital ghosts\nFading with every post\nSearching for something real\nIn a world that can't feel\nDigital ghosts\nConnected but alone\nA thousand friends at my fingertips\nBut no one to call my own\n\n[Bridge]\nIn this crowded digital space\nI'm screaming without a face\nCan anybody hear me now?\nOr am I just another ghost in the crowd?\nDisappearing bit by bit\nAs algorithms forget I exist\n\n[Chorus]\nWe're just digital ghosts\nFading with every post\nSearching for something real\nIn a world that can't feel\nDigital ghosts\nConnected but alone\nA thousand friends at my fingertips\nBut no one to call my own\n\n[Outro]\nDigital ghosts..."
        },
        {
            title: "Breaking Walls",
            style: "Progressive House, building vocals, dramatic drops, uplifting electronic elements, emotional chord progressions, powerful drums, anthemic structure, inspirational undertones",
            lyrics: "[Verse 1]\nBrick by brick I built these walls\nTo keep the world at bay\nTile by tile I laid the floor\nWhere only shadows play\nBut walls that shelter also trap\nKeep others and myself contained\nAnd in this fortress I've created\nOnly emptiness remains\n\n[Pre-Chorus]\nSo I'll start breaking down\nThese walls around my heart\nThough it terrifies me\nIt's time to make a start\n\n[Chorus]\nI'm breaking walls that I built so high\nLetting light flow in from the outside\nCracks appearing in my perfect disguise\nI'm breaking walls, breaking walls tonight\nEven if it hurts to feel again\nEven if I'm vulnerable within\nI can't live surrounded by these walls\nSo I'm breaking free, breaking through it all\n\n[Verse 2]\nThe first brick falls, I feel the sting\nOf air upon the wound\nExposed nerves that haven't felt\nFor oh so long, too soon\nBut with the pain comes something else\nA sense of being truly seen\nPerhaps there's life beyond these walls\nPerhaps there's more than I believed\n\n[Pre-Chorus]\nSo I'll keep breaking down\nThese walls around my heart\nThough it terrifies me\nIt's time to make a start\n\n[Chorus]\nI'm breaking walls that I built so high\nLetting light flow in from the outside\nCracks appearing in my perfect disguise\nI'm breaking walls, breaking walls tonight\nEven if it hurts to feel again\nEven if I'm vulnerable within\nI can't live surrounded by these walls\nSo I'm breaking free, breaking through it all\n\n[Bridge]\nWhat lies beyond this prison I've made?\nConnections waiting, unafraid\nThe world still turns despite my pain\nPerhaps it's time to live again\nRisk the hurt to feel the joy\nStep from shadow into light\n\n[Chorus]\nI'm breaking walls that I built so high\nLetting light flow in from the outside\nCracks appearing in my perfect disguise\nI'm breaking walls, breaking walls tonight\nEven if it hurts to feel again\nEven if I'm vulnerable within\nI can't live surrounded by these walls\nSo I'm breaking free, breaking through it all\n\n[Outro]\nBreaking walls... breaking free..."
        },
        {
            title: "Alone Together",
            style: "Emotional EDM, powerful vocals, cinematic orchestral elements, electronic build-ups, epic drops, inspirational progression, concluding anthemic qualities",
            lyrics: "[Verse 1]\nIn a world of disconnection\nWe're all fighting the same fight\nSix billion souls in isolation\nSearching for a light\nI used to think my loneliness\nWas something unique to me\nBut looking out my window now\nThe same pain I see\n\n[Pre-Chorus]\nWe're all staring at the same sky\nAll feeling the same pain\nAll hiding behind our walls\nAll calling out in vain\n\n[Chorus]\nWe're alone together\nSolitary stars in the same dark sky\nAlone together\nConnected by the tears we cry\nAlone together\nSilent voices forming one loud choir\nWe're alone, but we're alone together\nAnd that's enough to light the fire\n\n[Verse 2]\nYour room might look just like mine\nFour walls and a ceiling above\nEach person an island\nAll starving for love\nBut islands form archipelagos\nAnd stars form constellations bright\nPerhaps alone isn't truly alone\nWhen we're all sharing the night\n\n[Pre-Chorus]\nWe're all staring at the same sky\nAll feeling the same pain\nAll hiding behind our walls\nAll calling out in vain\n\n[Chorus]\nWe're alone together\nSolitary stars in the same dark sky\nAlone together\nConnected by the tears we cry\nAlone together\nSilent voices forming one loud choir\nWe're alone, but we're alone together\nAnd that's enough to light the fire\n\n[Bridge]\nReach your hand into the darkness\nYou'll find mine reaching back\nWe may never touch completely\nBut knowing you're there on a parallel track\nMakes the journey less frightening\nMakes the silence less deafening\nMakes the loneliness a shared experience\nAnd somehow that changes everything\n\n[Chorus]\nWe're alone together\nSolitary stars in the same dark sky\nAlone together\nConnected by the tears we cry\nAlone together\nSilent voices forming one loud choir\nWe're alone, but we're alone together\nAnd that's enough to light the fire\n\n[Outro]\nAlone together\nWe find strength in what we share\nAlone together\nWe find courage through despair\nAlone together..."
        }
    ]
};