// Define album data - making sure it's in the global (window) scope
window.ballads_of_blessing_data = {
    folder: "Ballads of Blessing",
    name: "Ballads of Blessing",
    releaseDate: "2025-04-05",
    totalSongs: 7,
    coverArt: "asset/album-name/Ballads of Blessing/Art.jpg",
    songsData: [
        {
            title: "Songs of Fire",
            style: "Epic folk rock with powerful percussion, driving rhythms, bold vocal delivery, heroic lute solos, war drums, resonant male choir backing, anthemic choruses, and fantasy-inspired battle themes",
            lyrics: "[Verse 1]\nStand tall as mountains, brave ones\nLet fire flow through your veins\nForged in battles long forgotten\nTempered like the finest steel\nMy song ignites the warrior's heart\nAnd makes the mighty kneel\n\n[Chorus]\nRise up with the strength of fire\nLet your muscles burn like flame\nSongs of fire, ever higher\nBreak the chains that hold you down\nSongs of fire, never tire\nWear your strength just like a crown\n\n[Verse 2]\nThe weight you bear seems lighter\nThe sword you wield feels right\nThe mountain's strength I grant you\nThe titan's force bestow\nMy melody of power\nMakes your true potential grow\n\n[Bridge]\nHear the ancient hymn of power\nPassed through bardic lore\nStrength of bear and bull and lion\nHear it now and roar!\n\n[Chorus]\nRise up with the strength of fire\nLet your muscles burn like flame\nSongs of fire, ever higher\nBreak the chains that hold you down\nSongs of fire, never tire\nWear your strength just like a crown\n\n[Outro]\nStrength of mountains\nForce of storms\nPower rising\nTransformed"
        },
        {
            title: "Wind's Whisper",
            style: "Celtic-inspired folk with swift flute melodies, nimble string arrangements, light percussion, airy vocals, dancing rhythms, breathless pacing, wind instruments, and flowing fingerpicked patterns",
            lyrics: "[Verse 1]\nFootsteps light as morning dew\nSwifter than the falcon's flight\nDancing through the battleground\nQuick as shadows in the night\nMy melody enhances grace\nAs swiftness flows within\n\n[Chorus]\nHear the wind's whisper through my strings\nFeel your body light as feathers\nWind's whisper, ever faster\nMoving like you're made of air\nWind's whisper, disaster master\nNone can catch you anywhere\n\n[Verse 2]\nThe thief who slips through shadows\nThe ranger's silent tread\nThe dodge that saves your life now\nThe parry just in time\nAll granted by the quickness\nBestowed through this rhyme\n\n[Bridge]\nSee the hummingbird's wings beating\nCatch the lightning as it strikes\nFeel the breeze through autumn leaves\nMy song grants movements of this like\n\n[Chorus]\nHear the wind's whisper through my strings\nFeel your body light as feathers\nWind's whisper, ever faster\nMoving like you're made of air\nWind's whisper, disaster master\nNone can catch you anywhere\n\n[Outro]\nFleet as starlight\nQuick as thought\nNimble fingers\nNever caught"
        },
        {
            title: "Mystic Melodies",
            style: "Ethereal progressive folk with complex harmonies, mystical harpsichord, intellectual chord progressions, magical sound design, crystalline female vocals, arcane instrumental sections, and philosophical lyrical themes",
            lyrics: "[Verse 1]\nAncient tomes and forgotten scrolls\nSpells and incantations flow\nThrough the chambers of your mind\nWisdom from a thousand sages\nThrough harmonies of arcane power\nYour perception grows so vast\n\n[Chorus]\nMystic melodies unveiling\nSecrets of the cosmic dawn\nMystic melodies, thought enhancing\nClarity beyond compare\nMystic melodies, mind advancing\nWisdom flowing through the air\n\n[Verse 2]\nThe wizard's spell precisely cast\nThe scholar's keen analysis\nPuzzles solved and traps detected\nLanguages now understood\nMemories enhanced, perfected\nThrough these songs of ancient wood\n\n[Bridge]\nConstellations of thought connecting\nDark becomes illuminated\nPatterns hidden now revealing\nMind and magic elevated\n\n[Chorus]\nMystic melodies unveiling\nSecrets of the cosmic dawn\nMystic melodies, thought enhancing\nClarity beyond compare\nMystic melodies, mind advancing\nWisdom flowing through the air\n\n[Outro]\nThoughts like diamonds\nMinds like stars\nWisdom ancient\nSees afar"
        },
        {
            title: "Stone's Patience",
            style: "Heavy folk with steady percussion, resilient bass lines, grounded vocals, stoic themes, deep drum rhythms, earth-toned instrumentation, unwavering tempo, and mountain-inspired melodic resilience",
            lyrics: "[Verse 1]\nStand firm as mountains, weather all storms\nLet my song be your foundation strong\nEndurance flowing through your core\nThe oak that bends but does not break\nMy melody of steadfast strength\nYour vulnerabilities sealed\n\n[Chorus]\nStone's patience, ever standing\nUnmovable as ancient hills\nStone's patience, lasting longer\nWhen others fall, you still remain\nStone's patience, growing stronger\nWeathering the fiercest pain\n\n[Verse 2]\nThe dwarf who mines through endless stone\nThe guardian who holds the line\nThe marathon beyond exhaustion\nThe burden carried mile on mile\nAll granted by resilience\nBestowed through bardic trial\n\n[Bridge]\nFeel the mountain's ancient power\nRooted deep within the earth\nSteady as the oldest boulder\nMy song grants endurance's worth\n\n[Chorus]\nStone's patience, ever standing\nUnmovable as ancient hills\nStone's patience, lasting longer\nWhen others fall, you still remain\nStone's patience, growing stronger\nWeathering the fiercest pain\n\n[Outro]\nSteady as mountains\nDeep as roots\nStrong as earth\nEnduring truth"
        },
        {
            title: "Verdant Verses",
            style: "Gentle pastoral folk with soothing harp, nurturing melodies, healing tonal qualities, nature-inspired arrangements, flowing water sounds, gentle female harmonies, restorative musical phrases, and rejuvenating rhythmic patterns",
            lyrics: "[Verse 1]\nClose your eyes and hear my song\nLet healing melodies flow through\nLike spring rain on parched earth\nWounds mending, pain subsiding\nMy verses green with life's renewal\nAs health through music swims\n\n[Chorus]\nVerdant verses, gently healing\nNature's touch within each note\nVerdant verses, pain relieving\nRestorative as morning dew\nVerdant verses, health retrieving\nHealing flowing back to you\n\n[Verse 2]\nThe cleric's prayer enhanced by sound\nThe natural healing of the body\nBlood flowing, tissues mending\nVitality restored in full\nGranted by the gift of healing\nThat these gentle notes instill\n\n[Bridge]\nHear the whisper of the willow\nFeel the blessing of the spring\nSense the power of renewal\nAs life flows through everything I sing\n\n[Chorus]\nVerdant verses, gently healing\nNature's touch within each note\nVerdant verses, pain relieving\nRestorative as morning dew\nVerdant verses, health retrieving\nHealing flowing back to you\n\n[Outro]\nHealing waters\nLife renewed\nPain surrenders\nStrength imbued"
        },
        {
            title: "Warrior's Refrain",
            style: "Martial folk anthem with military drums, bold brass section, inspiring chants, shield-striking percussion, battle-ready string arrangements, rallying male vocal harmonies, defensive musical motifs, and protective tonal qualities",
            lyrics: "[Verse 1]\nRaise your shields and stand your ground\nAs danger gathers all around\nMy song creates a wall of sound\nThe guardian's oath I amplify\nMy warrior's refrain empowers\nMaking spirits brave and bold\n\n[Chorus]\nWarrior's refrain surrounds you\nLike armor forged from purest steel\nWarrior's refrain, protection\nA shield of sound to keep you safe\nWarrior's refrain, direction\nCourage for the path you face\n\n[Verse 2]\nThe paladin who stands alone\nThe sentinel who guards the gate\nThrough darkest night till dawn\nAll strengthened by protective hymns\nFrom which courage is drawn\n\n[Bridge]\nHear the shields of ancient heroes\nFeel their courage through the years\nKnow the strength of those before you\nAs my song dispels your fears\n\n[Chorus]\nWarrior's refrain surrounds you\nLike armor forged from purest steel\nWarrior's refrain, protection\nA shield of sound to keep you safe\nWarrior's refrain, direction\nCourage for the path you face\n\n[Outro]\nStand as guardians\nFearless hearts\nShields unbroken\nHeroes start"
        },
        {
            title: "Symphony of Heroes",
            style: "Orchestral folk fusion with elements from all previous songs, triumphant arrangements, full choir, culminating themes, epic instrumental breaks, harmonic convergence, ceremonial percussion, and victorious crescendos",
            lyrics: "[Verse 1]\nGather now, brave adventurers\nAs my final song begins\nA symphony of perfect balance\nStrength and speed and wisdom flowing\nEndurance, healing, courage too\nAll attributes enhanced together\n\n[Pre-Chorus]\nFire and wind and mystic power\nStone and life and warrior's heart\nAll together, all united\nGreater than their separate parts\n\n[Chorus]\nSymphony of heroes rising\nEvery blessing now combined\nSymphony of heroes, glory\nLegends born within this sound\nSymphony of heroes, story\nVictories soon to be found\n\n[Verse 2]\nThe raid that faces final challenge\nThe fellowship in darkest dungeon\nOn whom all hopes depend\nThe balance of all attributes\nGranted by this ultimate blessing\nOf bardic symphony\n\n[Bridge]\nHear the echoes of all songs before\nMerged in perfect harmony\nFeel the fullness of potential\nAs you become who you're meant to be\n\n[Chorus]\nSymphony of heroes rising\nEvery blessing now combined\nSymphony of heroes, glory\nLegends born within this sound\nSymphony of heroes, story\nVictories soon to be found\n\n[Outro]\nHeroes ascending\nLegends born\nPowers blending\nFate transformed"
        }
    ]
};