// Define album data - making sure it's in the global (window) scope
window.chronicles_of_the_azure_guardian_data = {
    folder: "Chronicles Of The Azure Guardian",
    name: "Chronicles Of The Azure Guardian",
    releaseDate: "2025-03-11",
    totalSongs: 7,
    coverArt: "asset/album-name/Chronicles Of The Azure Guardian/Art.jpg",
    songsData: [
        {
            title: "Awakening of Azure",
            style: "Epic orchestral with electronic elements, atmospheric synth layers, haunting vocal chants, cinematic percussion, ethereal string arrangements, medieval instrumentation undertones, powerful crescendos, mystical sound design.",
            lyrics: "[Verse 1]\nCold wind howls through ancient pines\nAs darkness falls on hallowed ground\nA sword of light in shadow's shroud\nThe guardian rises, duty bound\n\n[Pre-Chorus]\nBeneath the moonlit mountains high\nWhere legends sleep and secrets lie\nThe door awaits, its lantern glows\nThe path begins where no one goes\n\n[Chorus]\nAzure flame, eternal light\nBreaking through the endless night\nGuardian of the sacred door\nAwakened now to fight once more\n\n[Verse 2]\nWith blade in hand and purpose clear\nThe chosen one must persevere\nThrough winter's grip and forests deep\nAncient vows and oaths to keep\n\n[Chorus]\nAzure flame, eternal light\nBreaking through the endless night\nGuardian of the sacred door\nAwakened now to fight once more\n\n[Bridge]\nBeyond the veil, beyond the known\nWhere mortals fear to walk alone\nThe guardian stands at threshold's edge\nBound by blood and solemn pledge\n\n[Outro]\nThe journey starts with first light drawn\nThe Azure Guardian greets the dawn\nA lonely figure, cloaked in fate\nThe sentinel at destiny's gate"
        },
        {
            title: "The Calling",
            style: "Driving epic metal with folk elements, powerful vocals, heroic guitar riffs, medieval instrumentation, rhythmic war drums, symphonic orchestration, mystical chanting, dynamic tempo changes, harmonic minor scale progressions.",
            lyrics: "[Verse 1]\nAncient scrolls foretold the day\nWhen darkness would consume the land\nThe chosen one with azure blade\nLast of an order, make their stand\nWhispers echo through the trees\nA calling that I cannot fight\nDestiny has chosen me\nTo bear this burden, wield this light\n\n[Pre-Chorus]\nBeyond that threshold lies the truth\nThe path that I alone must walk\nThrough trials of fire and blood and stone\nWhere greater powers darkly stalk\n\n[Chorus]\nI am the Guardian, sworn to protect\nThe barrier between worlds, the veil held in check\nWith azure light to guide my way\nI'll face what others fear to name\nThe calling burns inside my veins\nI cannot turn away\n\n[Verse 2]\nMountains watch with silent gaze\nAs I approach the ancient door\nWhere others fell in bygone days\nTheir warnings etched in stone and lore\nThe lantern burns with fading hope\nA beacon in this wilderness\nThe weight of worlds upon my cloak\nAs I prepare for this dark quest\n\n[Chorus]\nI am the Guardian, sworn to protect\nThe barrier between worlds, the veil held in check\nWith azure light to guide my way\nI'll face what others fear to name\nThe calling burns inside my veins\nI cannot turn away\n\n[Bridge]\nAncestors watch from shadows deep\nTheir whispered wisdom in the wind\n\"The path ahead is steep and bleak\nBut fail, and all the world is dimmed\"\n\n[Outro]\nThe door awaits, my sword alight\nThe calling echoes through the night\nOne final breath before the plunge\nInto the depths where demons lunge"
        },
        {
            title: "Beyond the Gate",
            style: "Intense battle metal, aggressive percussion, choir-backed choruses, dueling guitars, operatic vocal highlights, dramatic tempo shifts, cinematic sound effects, haunting string interludes, thunderous bass drops, ambient dark atmosphere breaks.",
            lyrics: "[Verse 1]\nThe ancient door creaks open wide\nRevealing what was kept inside\nA realm of shadows, frozen time\nWhere eldritch horrors slowly climb\nThe azure blade cuts through the dark\nIlluminating where I tread\nThe guardians who came before\nTheir bones now line the pathway ahead\n\n[Pre-Chorus]\nThere's no returning, no retreat\nThe gate has locked behind my feet\nThe only path is forward now\nThrough darkness deep, I must endow\n\n[Chorus]\nBeyond the gate where nightmares dwell\nMy azure light against their hell\nStanding firm where others fell\nThe battle cries begin to swell\nGuardian of the sacred threshold\nWith every strike my purpose told\nThrough shadow realms and chaos old\nA hero's journey now unfolds\n\n[Verse 2]\nAncient evils stir and rise\nWith hatred burning in their eyes\nDrawn to power, drawn to light\nThey gather for unholy fight\nMy blade sings out with righteous fire\nEach swing a promise, each cut desire\nTo cleanse this place of ancient wrong\nAnd prove the guardians still strong\n\n[Chorus]\nBeyond the gate where nightmares dwell\nMy azure light against their hell\nStanding firm where others fell\nThe battle cries begin to swell\nGuardian of the sacred threshold\nWith every strike my purpose told\nThrough shadow realms and chaos old\nA hero's journey now unfolds\n\n[Bridge]\nThe shadows press from every side\nNo place to run, nowhere to hide\nBut in this darkness, I find strength\nMy resolve growing at great length\nFor I am more than flesh and bone\nMore than a warrior alone\nI am the heir to azure flame\nThe guardian that darkness fears to name\n\n[Outro]\nThe battle rages through the night\nMy blade a beacon of blue light\nBeyond the gate the truth awaits\nAs destiny seals the guardian's fate"
        },
        {
            title: "Legacy of Light",
            style: "Introspective power ballad with progressive metal elements, emotional vocal delivery, atmospheric keyboards, clean guitar passages building to powerful distorted choruses, symphonic backing, dynamic range from quiet contemplation to powerful determination.",
            lyrics: "[Verse 1]\nIn the calm between the storms\nAs enemies retreat to shadows\nI catch my breath, inspect my wounds\nAnd contemplate what lies below\nThe azure blade, its light now dimmed\nReflects the doubt within my eyes\nHow many guardians came before?\nHow many fell, how many died?\n\n[Pre-Chorus]\nAncient memories not my own\nFlow through the sword into my soul\nThe legacy of light revealed\nAs visions of the past unfold\n\n[Chorus]\nI am not the first to bear this light\nNot the first to wage this endless fight\nThrough my veins runs the blood of guardians old\nTheir strength, their courage, their stories untold\nLegacy of light, burning through time\nTheir sacrifice becomes now mine\nI stand renewed, their power my own\nNo longer fighting alone\n\n[Verse 2]\nThe sword begins to pulse and glow\nAs whispers of the fallen speak\nTheir trials, triumphs, final stands\nTheir wisdom now is what I seek\n\"The path ahead grows darker still\nThe greatest test awaits beyond\nRemember why you bear the blade\nRemember to what you've sworn\"\n\n[Chorus]\nI am not the first to bear this light\nNot the first to wage this endless fight\nThrough my veins runs the blood of guardians old\nTheir strength, their courage, their stories untold\nLegacy of light, burning through time\nTheir sacrifice becomes now mine\nI stand renewed, their power my own\nNo longer fighting alone\n\n[Bridge]\nThe faces of a thousand years\nFlash before my weary eyes\nEach guardian who held this sword\nEach warrior who sacrificed\nTheir essence flows through azure steel\nTheir purpose merging now with mine\nThe burden shared across the ages\nA constellation through dark times\n\n[Outro]\nThe blade glows brighter than before\nAs I embrace what came before\nThe legacy of azure light\nEmpowers me to win this fight\nNo longer just a chosen one\nBut heir to all that's been done\nGuardian of past and future both\nI rise again, renewed by hope"
        },
        {
            title: "Heart of Darkness",
            style: "Epic battle metal with symphonic elements, aggressive rhythms, dual guitar harmonies, theatrical vocals, orchestral backing, choir accents, dramatic tempo shifts, powerful double bass drums, triumphant melodic hooks.",
            lyrics: "[Verse 1]\nDeep where ancient evil dwells\nWhere chaos takes its primal form\nThe source of shadows, hate distilled\nWhere light itself was torn and sworn\nA thousand years it's waited here\nThe reason guardians fought so long\n\n[Pre-Chorus]\nFace to face with destiny\nAzure against abyssal black\nThe final test of worth\nA battle for the earth\n\n[Chorus]\nHeart of Darkness, pulsing might\nAgainst my azure burning light\nTwo forces locked in timeless war\nThis is what I was chosen for\nGuardian's oath, fulfilled in fire\nAs blade meets darkness, rising higher\n\n[Verse 2]\nIt speaks in voices cold and sweet\nOf failure, death, and surrender\nBut through my veins the azure flows\nThe legacy of light unbroken\nMy resolve hardens like steel\nAs words of power are spoken\n\n[Chorus]\nHeart of Darkness, pulsing might\nAgainst my azure burning light\nTwo forces locked in timeless war\nThis is what I was chosen for\nGuardian's oath, fulfilled in fire\nAs blade meets darkness, rising higher\n\n[Bridge]\nThe chamber shakes with primal rage\nAs darkness summons final power\nMy sword raised high, a final strike\nAll strength and will behind the blow\n\n[Outro]\nThe collision of ancient powers\nLight and dark in fatal hours\nGuardian's duty, nearly done\nThe heart of darkness, nearly won"
        },
        {
            title: "The Price of Victory",
            style: "Melodic progressive metal with atmospheric elements, emotional vocals alternating between vulnerable verses and powerful choruses, thoughtful guitar work, ambient keyboards, reflective dynamics, somber yet hopeful undertones, symphonic flourishes.",
            lyrics: "[Verse 1]\nAs darkness fades away\nAnd azure light begins to dim\nThe cost of victory reveals itself\nIn wounds both seen and within\nThe chamber crumbles around\nThe ancient evil now undone\nWhat remains of who I was\nBefore this journey had begun?\n\n[Pre-Chorus]\nEvery guardian pays a price\nA piece of soul, a fragment lost\nVictory never comes without cost\n\n[Chorus]\nThe price of victory etched in scars\nA hero's burden, a warrior's toll\nWhat was given can't be returned\nBut I would pay it all again\nFor light to overcome the dark\nThough victory leaves its mark\n\n[Verse 2]\nI gather strength to stand once more\nThe path home seems distant now\nThe azure blade, now part of me\nOur fates forever intertwined\nThe power fading, purpose served\nUntil darkness rises once again\n\n[Chorus]\nThe price of victory etched in scars\nA hero's burden, a warrior's toll\nWhat was given can't be returned\nBut I would pay it all again\nFor light to overcome the dark\nThough victory leaves its mark\n\n[Bridge]\nWas I chosen by the blade?\nOr did I choose this path of pain?\nThe guardian before me knew\nThe sacrifice that must be made\nAs will the one who follows next\n\n[Outro]\nThrough ancient doorways, homeward bound\nThe price of victory I have paid\nThe world continues, unknowing still\nOf battles fought beyond the veil\nThe silent guardian returns alone"
        },
        {
            title: "Eternal Vigil",
            style: "Epic symphonic metal with folk elements, triumphant yet reflective, soaring vocal harmonies, powerful orchestration, heroic guitar themes, ritual percussion, choral backing, ceremonial atmosphere, emotional dynamic range.",
            lyrics: "[Verse 1]\nThe ancient door now sealed once more\nI stand beneath the mountain sky\nThe azure blade now dormant sleeps\nAgainst my battle-worn frame\nAnother chapter in the endless tale\nOf guardians who bear the flame\n\n[Pre-Chorus]\nNot all heroes are remembered\nNot all victories sung in halls\nSome battles remain as secrets\nHidden behind sacred walls\n\n[Chorus]\nEternal vigil, endless watch\nThough this battle has been won\nAnother will begin again\nGuardian of the azure light\nSentinel between the worlds\nUntil my duty is fulfilled\n\n[Verse 2]\nThe village sleeps in valley's embrace\nUnknowing of the threats beyond\nThe burden lightens with each step\nToward home and healing rest\nUntil the blade calls once again\nTo face another deadly test\n\n[Bridge]\nThrough generations, time untold\nThe azure guardians stand as one\nA lineage of chosen souls\nWe are the shields that block the night\nEnsuring light will never fail\n\n[Final Chorus]\nEternal vigil, sacred trust\nFrom ancient past to days unknown\nThe azure flame, a beacon bright\nGuardian now and evermore\nUntil another takes the fight\n\n[Outro]\nThe lantern by the ancient door\nWill burn until the end of days\nChronicles of light continue on\nThe sentinel returns to watch\nThe sacred threshold, oath to keep"
        }
    ]
};