// Define album data - making sure it's in the global (window) scope
window.syair_taman_ilahi_data = {
    folder: "Syair Taman Ilahi",
    name: "Syair Taman Ilahi",
    releaseDate: "2025-02-25",
    totalSongs: 7,
    coverArt: "asset/album-name/Syair Taman Ilahi/Art.jpg",
    songsData: [
        {
            title: "Cahaya Syurga",
            style: "Ethereal Malay ballad, Ambient orchestral arrangements, Traditional folk elements, Atmospheric synthesizers, Building percussion, Gentle vocals, Cinematic crescendos, Sacred harmonies",
            lyrics: "[Verse 1]\nDalam kebun yang terbentang\nCahaya syurga menerangi\nSeorang gadis yang termenung\nDi balik jendela suci\n\n[Pre-chorus]\nSinar menari lembut\nMelalui daun yang rimbun\nMembawa pesan kudus\n\n[Chorus]\nWahai cahaya dari-Nya\nSinari jiwa yang setia\nBiar dunia tak mengerti\nKau tetap menyinari\nDalam taman ini\nKu temui makna\n\n[Verse 2]\nDedaunan menari lembut\nMenyambut sang bidadari\nYang tersenyum dalam sunyi\nMenyimpan rahsia ilahi\n\n[Bridge]\nDi antara siang dan senja\nDimana insan bertemu cahaya\nKu lihat kebenaran mekar\nSeperti bunga di pagi hari\n\n[Outro]\nDalam kebun yang damai\nDimana cahaya bersemi\nKu temui kedamaian\nYang tak akan berakhir\n(Yang tak berakhir...)"
        },
        {
            title: "Luminous Wanderer",
            style: "Progressive rock, Symphonic metal elements, Dream pop atmospheres, Gothic choir harmonies, Electronic undertones, Dramatic string arrangements",
            lyrics: "[Verse 1]\nThrough burning clouds I roam\nWhere ravens dance and soar\nFootsteps echo void\nAs heaven's door unfolds\nStanding beneath the storm\nOf wings that paint the day\n\n[Pre-chorus]\nMy path dissolves in gold\nAs shadows fade away\n\n[Chorus]\nWanderer of dawn\nWhere light meets shade\nRavens guide me on\nThrough amber haze\nIn this moment here\nBetween now and then\nMorning light reveals\nWhat sets me free\n\n[Verse 2]\nThose who follow fade\nLike ghosts against the flame\nRavens circle closer\nWhisper secrets unnamed\nIn twilight's theater\nWhere all things change\n\n[Pre-chorus]\nEach wingbeat marks time's flow\nAs night turns into day\n\n[Chorus]\nWanderer of dawn\nWhere light meets shade\nRavens guide me on\nThrough amber haze\nIn this moment here\nBetween now and then\nMorning light reveals\nWhat sets me free\n\n[Bridge]\nAt the crossroads where\nDark meets light\nYesterday's shadows\nTake to flight\nRavens paint their tales\nIn skies of gold\nAs dawn awakens\nStories untold\n\n[Outro]\nToward horizons burning\nRavens lead the way\nEach step transforming\nInto breaking day\n(Into breaking day...)"
        },
        {
            title: "Among the Embers",
            style: "Dark ambient post-rock, Cinematic orchestration, Industrial percussion elements, Atmospheric synthesizers, Gothic choral arrangements",
            lyrics: "[Verse 1]\nBurning embers paint the sky\nAs dark wings circle high\nDistant figures fade to shadows\nOn paths I leave behind\nWhile ravens dance above\nIn mind's own theater\n\n[Pre-chorus]\nAt twilight's burning edge\nWhere wingbeats tell their tales\nOf secrets yet untold\n\n[Chorus]\nInto the fire I walk\nThrough amber clouds aflame\nWhere ravens spread their wings\nIn apocalypse ballet\nAs dawn ignites the heavens\nAnd night burns away\n\n[Verse 2]\nSilhouettes against sunrise\nCast shapes across my soul\nWhere dark meets burning light\nMessengers take flight\nIn this moment changing\nNew stories unfold\n\n[Chorus]\nInto the fire I walk\nThrough amber clouds aflame\nWhere ravens spread their wings\nIn apocalypse ballet\nAs dawn ignites the heavens\nAnd night burns away\n\n[Bridge]\nBetween existence veils\nWhere light meets darkened air\nRavens guide my steps through\nYesterday's farewell\nAs shadows turn to flame\nNothing stays the same\n\n[Outro]\nStanding at the threshold\nWhere what was meets will be\nRavens paint the morning\nIn dark serenity\n(Through burning skies...)"
        },
        {
            title: "Symphony of Ravens",
            style: "Orchestral rock fusion, Dark ambient textures, Epic film score elements, Dramatic percussion, Gothic choir harmonies",
            lyrics: "[Verse 1]\nThrough burning skies a soul walks on\nWhile ravens dance their dark ballet\nWhere sunset bleeds to endless night\nAnd wings paint heaven's stage\nA thousand birds in silent flight\nAs twilight turns its page\n\n[Pre-chorus]\nWhere the world transforms\nBetween light and shade\nAs the sky performs\nIts light cascade\n\n[Chorus]\nIn ravens' symphony\nWhere embers fly\nWings beat like hearts\nAgainst burning sky\nThrough frozen moments\nTime fades away\nAs dark birds guide me\nThrough breaking day\n\n[Verse 2]\nGhosts fade behind my form\nWhile ravens weave gold storms\nEach step leads deeper in\nWhere heaven's flames begin\nAs shadows write their tales\nThrough amber-tinted veils\n\n[Bridge]\nWhere light and darkness meet\nOn twilight's throne\nRavens paint old paths\nThrough skies of gold\nEach feather tells of ends\nAnd new begins\nAs morning transforms all\nIn dark-winged dance\n\n[Chorus]\nIn ravens' symphony\nWhere embers fly\nWings beat like hearts\nAgainst burning sky\nThrough frozen moments\nTime fades away\nAs dark birds guide me\nThrough breaking day\n\n[Outro]\nThrough the threshold where\nReality burns bright\nLed by ravens' wings\nInto golden light\n(Through the ravens' flight...)"
        },
        {
            title: "Sunset's Ravens Dance",
            style: "Atmospheric rock, Dark folk elements, Cinematic orchestration, Ambient synthesizer layers, Trip-hop percussion",
            lyrics: "[Verse 1]\nBurning clouds like molten gold\nPaint silhouettes above\nRavens soar through amber waves\nWhere sun and darkness merge\nStanding still to watch them fly\nEach bird a stroke of night\nIn twilight's fading canvas\nAs two worlds unite\n\n[Pre-chorus]\nOthers fade behind\nLike shadows in the maze\nWhile ravens guide me\nThrough golden haze\n\n[Chorus]\nDark wings circle high\nThrough burning air\nAs twilight sets\nHeaven's light aflame\nIn this moment where\nTime stands still\nRavens dance as\nDestiny waits\n\n[Verse 2]\nFeathers cut through sunset's glow\nLike ink in golden seas\nBirds circle watchful, close and low\nThe sky ignites with flames\nOf amber, rust, and burning gold\nAs ravens pierce the dusk\n\n[Bridge]\nBetween the worlds\nWhere light meets shade\nRavens keep their watch\nAs old times fade\nEach wing marks moments\nTurned to gold\nAs dawn reveals\nNew tales untold\n\n[Chorus]\nDark wings circle high\nThrough burning air\nAs twilight sets\nHeaven's light aflame\nIn this moment where\nTime stands still\nRavens dance as\nDestiny waits\n\n[Outro]\nToward tomorrow's gold\nRavens lead the way\nNew stories unfold\n(Through the burning day...)"
        },
        {
            title: "Crown of Ravens",
            style: "Epic rock fusion, Ethereal ambient textures, Cinematic orchestration, Dark folk elements, Industrial percussion",
            lyrics: "[Verse 1]\nWings become my golden crown\nWhere destinies unfold\nEach raven bears its sacred truth\nThrough skies of burning gold\nBefore the flaming veil I stand\nWhere all dissolves to light\nAs dark birds circle overhead\nLike guardians of night\n\n[Pre-chorus]\nThrough embers of the day\nRavens weave their spells\nAncient wisdom guides me\nThrough the tales they tell\n\n[Chorus]\nCrowned in wings of darkness\nIn this light divine\nRavens dance through amber\nMaking night to day\nEach feather shares its story\nAs heaven burns around\nGuiding me back home\n\n[Verse 2]\nProphecy fills golden skies\nAs ravens teach me flight\nTime bends in this crucible\nWhere wisdom paints the light\nThrough horizons strange and new\nTheir knowledge flows to one\n\n[Bridge]\nBetween what was and will\nWhere change reigns supreme\nRavens share their secrets\nThrough golden-burning dreams\nEach moment brings new sight\nAs shadows turn to flame\nThrough realms beyond all names\n\n[Chorus]\nCrowned in wings of darkness\nIn this light divine\nRavens dance through amber\nMaking night to day\nEach feather shares its story\nAs heaven burns around\nGuiding me back home\n\n[Outro]\nWearing wisdom's wings\nThrough liquid gold above\nLed by ravens' truth\nAs new worlds unfold\n(Through the burning scroll...)"
        },
        {
            title: "The Final Flight",
            style: "Epic orchestral rock, Symphony layers, Ascending choral harmonies, Metal elements, Building Cinematic percussion, Multiple Guitar harmonies, Pipe organ, Sacred music, Grand crescendos",
            lyrics: "[Verse 1]\nAt revelation's edge\nAll paths merge to gold\nRavens form their ranks\nAs ancient tales unfold\nEach wing bears witness\nTo changes deep within\nWhile burning skies tell\nWhere endings begin\n\n[Pre-chorus]\nAt the crossroads where\nPast meets destiny\nRavens weave together\nWhat I'm meant to see\n\n[Chorus]\nThe final testament\nIn burning air\nEvery raven's wisdom\nTruth laid bare\nThrough golden fire\nMessages arise\nAs heaven's pages burn\nAnd secrets rise\n\n[Verse 2]\nDark messengers taught\nThrough amber-dancing light\nReading sacred flames\nWhere day turns to night\nTheir wings surround me\nIn crystal moments clear\nAs truth emerges\nAnd walls disappear\n\n[Bridge]\nThrough dawns and wings\nThrough twilight's dance\nAll paths now merge\nAll stories chance\nAs heaven burns\nAnd mysteries wind\nInto one truth\nWe're meant to find\n\n[Crescendo]\nLet dark wings guide me\nLet flames reveal\nLet truth transform me\nAs we all heal\nWhile ravens paint\nAcross burning sky\nTeaching us at last\nTeaching us to fly\n\n[Outro]\nTestament now sealed\nIn flame and gold\nRavens lead ahead\nThrough tales untold\n(Through skies of gold...)\n(The tale is told...)"
        }
    ]
};