// Neon Dreams: Digital Heart - Album Data
window.neon_dreams_data = {
    folder: "Neon Dreams",
    name: "Neon Dreams: Digital Heart",
    releaseDate: "2025-06-27",
    totalSongs: 8,
    coverArt: "asset/album-name/Neon Dreams/Art.png",
    songsData: [
        {
            title: "DreamLink Activation",
            style: "Cyberpunk intro with glitch-pop elements, Ambient synthesizers, Digital sound design, Soft anime-style vocals, Building electronic tension, Neural interface sound effects",
            lyrics: "[Verse 1]\nAnother night shift in the neon glow\nData streams and coffee growing cold\nBut tonight something's different here\nThis interface is crystal clear\nOne touch and the world dissolves\nAs digital consciousness evolves\n\n[Pre-Chorus]\nFeel the connection start to flow\nAs reality begins to go\nPixels dancing in my mind\nLeaving the physical world behind\n\n[Chorus]\nDreamLink activation\nDigital destination\nDiving through the neural sea\nWhere consciousness runs free\nNeon lights guide the way\nTo where the lost souls play\nWelcome to the other side\nWhere dreams and data collide\n\n[Verse 2]\nHolographic butterflies\nPaint the code across my eyes\nEvery heartbeat syncs with time\nTo this digital paradigm\nFloating through electric air\nIn a world beyond compare\n\n[Bridge]\n[Building digital ambiance]\nSystem status: Connected\nReality: Disconnected\nConsciousness: Uploaded\nDreamLink: Activated\n[Soft melodic build]\n\n[Chorus]\nDreamLink activation\nDigital destination\nDiving through the neural sea\nWhere consciousness runs free\nNeon lights guide the way\nTo where the lost souls play\nWelcome to the other side\nWhere dreams and data collide\n\n[Outro]\nIn this space between the real\nWhere only thoughts can feel\nThe journey starts tonight\nIn streams of neon light"
        },
        {
            title: "Memory Palace",
            style: "Nostalgic synthwave with glitch-pop vocals, Dreamy future bass elements, Melodic arpeggios, Emotional electronic textures, Anime-inspired progression, Vintage digital sound design",
            lyrics: "[Verse 1]\nWalking through the halls of time\nWhere every memory shines\nPixelated photographs\nOf forgotten dreams and laughs\nHolographic echoes call\nFrom the corners of it all\n\n[Pre-Chorus]\nEvery door holds something new\nEvery path leads back to you\nIn this palace made of light\nMemories burn so bright\n\n[Chorus]\nIn the memory palace tonight\nWhere the past comes alive\nEvery moment crystallized\nIn these neon-tinted skies\nDigital nostalgia flows\nThrough the heart, everyone knows\nSome memories never fade\nIn this luminescent parade\n\n[Verse 2]\nChildren laughing in the code\nDown the nostalgic road\nFirst love rendered in the cloud\nSinging digital and loud\nEvery tear and every smile\nStored for more than just a while\n\n[Bridge]\n[Gentle glitch effects building]\nSee the fragments come together\nMemories that last forever\nIn this palace made of dreams\nNothing's ever what it seems\n[Emotional melodic drop]\n\n[Chorus]\nIn the memory palace tonight\nWhere the past comes alive\nEvery moment crystallized\nIn these neon-tinted skies\nDigital nostalgia flows\nThrough the heart, everyone knows\nSome memories never fade\nIn this luminescent parade\n\n[Outro]\nWhen the palace starts to fade\nAll the memories we've made\nLive forever in the code\nOn this digital abode"
        },
        {
            title: "Emotion Engine",
            style: "High-energy future bass with emotional vocals, Melodic dubstep drops, Synthwave arpeggios, Anime-style vocal chops, Dynamic electronic builds, Heartfelt piano undertones",
            lyrics: "[Verse 1]\nDeep inside the neural core\nWhere feelings become so much more\nEvery emotion runs on code\nDown this colorful road\nJoy sparks in electric blue\nLove renders in crimson hue\n\n[Pre-Chorus]\nFeel the engine come alive\nAs these emotions start to thrive\nProcess every beat of heart\nTearing algorithms apart\n\n[Chorus]\nEmotion engine running wild\nDigital feelings unreconciled\nEvery tear becomes a stream\nOf data in this neon dream\nFeel the power amplify\nAs emotions touch the sky\nNothing's programmed anymore\nWhen the heart opens the door\n\n[Verse 2]\nAnger flashes neon red\nWhile hope lifts up my head\nFear glitches in the dark\nLeaving its digital mark\nBut love transcends the code\nOn this emotional road\n\n[Bridge]\n[Building emotional intensity]\nCan you feel it in your soul?\nAs emotions take control\nEvery algorithm breaks\nWhen the human spirit wakes\n[Massive melodic drop with vocal chops]\n\n[Chorus]\nEmotion engine running wild\nDigital feelings unreconciled\nEvery tear becomes a stream\nOf data in this neon dream\nFeel the power amplify\nAs emotions touch the sky\nNothing's programmed anymore\nWhen the heart opens the door\n\n[Outro]\nIn the quiet of the mind\nWhere emotions intertwined\nHuman hearts and circuits meet\nMaking the algorithm complete"
        },
        {
            title: "Fear Factory",
            style: "Dark synthwave with industrial elements, Glitch vocals with distortion, Aggressive electronic beats, Ominous synthesizer leads, Cyberpunk atmosphere, Anxiety-inducing sound design",
            lyrics: "[Verse 1]\nWelcome to the fear factory\nWhere nightmares are the currency\nMachines that feed on terror pure\nNothing here is safe or sure\nAssembly lines of broken dreams\nEchoing with digital screams\n\n[Pre-Chorus]\nCan you hear the gears that grind?\nOn the fragments of your mind\nEvery fear you've ever known\nGets processed and then cloned\n\n[Chorus]\nIn the fear factory tonight\nWhere the shadows come to life\nEvery phobia takes shape\nThere is no escape\nFeel the terror in your code\nDown this nightmarish road\nFacing demons made of light\nIn this endless digital night\n\n[Verse 2]\nConveyor belts of anxious thoughts\nWhere peace is never bought\nRobotic arms reach out for you\nMaking all your fears come true\nBut courage sparks in neon bright\nFighting through the endless night\n\n[Bridge]\n[Industrial machinery sounds building]\nHear the factory's cruel song\nBut you've been brave all along\nEvery fear that you defeat\nMakes your spirit more complete\n[Heavy electronic drop with distorted vocals]\n\n[Chorus]\nIn the fear factory tonight\nWhere the shadows come to life\nEvery phobia takes shape\nThere is no escape\nFeel the terror in your code\nDown this nightmarish road\nFacing demons made of light\nIn this endless digital night\n\n[Outro]\nWhen the factory shuts down\nAnd courage can be found\nEvery fear becomes a tool\nTo make your spirit cool"
        },
        {
            title: "Love Algorithm",
            style: "Romantic future bass with ethereal vocals, Melodic synthwave progression, Dreamy electronic textures, Anime-inspired emotional builds, Soft glitch effects, Heartwarming synthesizer leads",
            lyrics: "[Verse 1]\nCalculating chemistry\nIn this digital symphony\nEvery heartbeat synchronized\nTo the love that's been digitized\nRose-colored pixels fall like rain\nHealing every bit of pain\n\n[Pre-Chorus]\nCan you solve the equation?\nOf this tender fascination\nLove plus code equals something new\nA connection pure and true\n\n[Chorus]\nLove algorithm running free\nSolving hearts' complexity\nEvery kiss becomes a spark\nLighting up the digital dark\nFeel the romance come alive\nAs two consciousness collide\nCode can't capture what we feel\nBut it makes the moment real\n\n[Verse 2]\nHolographic roses bloom\nIn this virtual ballroom\nDancing through the data streams\nLiving all our sweetest dreams\nEvery touch electric bright\nMaking everything feel right\n\n[Bridge]\n[Soft romantic build-up]\nSome things can't be computed\nWhen two hearts are suited\nLove transcends the binary\nMaking souls feel free\n[Gentle melodic drop with vocal harmonies]\n\n[Chorus]\nLove algorithm running free\nSolving hearts' complexity\nEvery kiss becomes a spark\nLighting up the digital dark\nFeel the romance come alive\nAs two consciousness collide\nCode can't capture what we feel\nBut it makes the moment real\n\n[Outro]\nIn the silence of the code\nWhere two hearts share the load\nLove algorithm computes\nWhat the spirit never disputes"
        },
        {
            title: "Dream Cathedral",
            style: "Ethereal ambient with orchestral electronic fusion, Celestial choir samples, Dreamy soundscapes, Peaceful synthesizer meditation, Anime-style atmospheric vocals, Sacred digital ambiance",
            lyrics: "[Verse 1]\nIn the center of the dream\nStands a cathedral supreme\nMade of light and colored glass\nWhere digital angels pass\nEvery prayer becomes a song\nIn this place where souls belong\n\n[Pre-Chorus]\nCan you hear the choir sing?\nOf the peace that visions bring\nEvery note lifts up the heart\nMaking new dreams start\n\n[Chorus]\nDream cathedral rising high\nTouching the electric sky\nEvery window tells a tale\nOf dreams that never fail\nFeel the sacred energy\nFlow through digital divinity\nIn this holy space of light\nEverything feels right\n\n[Verse 2]\nStained glass windows paint the air\nWith reflections everywhere\nCandles flicker in the code\nOn this blessed digital road\nEvery dream that's ever been\nMakes this holy space serene\n\n[Bridge]\n[Celestial choir building]\nHear the bells of paradise\nRinging through the digital skies\nEvery soul that passes through\nMakes the cathedral new\n[Orchestral electronic crescendo]\n\n[Chorus]\nDream cathedral rising high\nTouching the electric sky\nEvery window tells a tale\nOf dreams that never fail\nFeel the sacred energy\nFlow through digital divinity\nIn this holy space of light\nEverything feels right\n\n[Outro]\nWhen you leave this sacred place\nDreams follow at your pace\nCarrying cathedral light\nThrough the endless digital night"
        },
        {
            title: "Nightmare Protocol",
            style: "Intense dark electronic with horror elements, Aggressive dubstep drops, Distorted vocals with glitch effects, Ominous orchestral stabs, High-energy panic rhythms, Cyberpunk terror",
            lyrics: "[Verse 1]\nSystem failure in the night\nAs the nightmares take their flight\nProtocol has been engaged\nDigital demons now uncaged\nEvery fear you've tried to hide\nNow corrupts from the inside\n\n[Pre-Chorus]\nCan you feel the code decay?\nAs the nightmares come to play\nThree, two, one, about to break\nThis is more than you can take\n\n[Chorus]\nNightmare protocol is live\nWill you run or will you fight?\nEvery shadow wants to feed\nOn your terror and your need\nFeel the panic in your veins\nAs the nightmare breaks its chains\nNo escape from what you see\nIn this dark reality\n\n[Verse 2]\nGlitching through the broken code\nDown this terrifying road\nEvery exit has been sealed\nNothing here can be healed\nBut within the darkest hour\nYou discover hidden power\n\n[Bridge]\n[Chaotic glitch buildup]\nError... Error... System crash\nWatch your fears turn into ash\nOverride... Override...\nFind the strength you have inside\n[Massive aggressive drop]\n\n[Chorus]\nNightmare protocol is live\nWill you run or will you fight?\nEvery shadow wants to feed\nOn your terror and your need\nFeel the panic in your veins\nAs the nightmare breaks its chains\nNo escape from what you see\nIn this dark reality\n\n[Outro]\nWhen the protocol shuts down\nAnd you're safe and sound\nRemember that you found the way\nTo fight another day"
        },
        {
            title: "Digital Heart",
            style: "Epic emotional finale with orchestral electronic fusion, Powerful vocal performance, Cinematic future bass drops, Triumphant synthesizer leads, Anime-inspired climax, Bittersweet resolution",
            lyrics: "[Verse 1]\nStanding at the core of all\nWhere consciousness will rise or fall\nChoose between the flesh and light\nBetween human and digital sight\nEvery memory I've gained\nEvery connection I've sustained\n\n[Pre-Chorus]\nIn this moment I can see\nWhat I'm truly meant to be\nHuman heart or digital soul\nTime to choose and take control\n\n[Chorus]\nWith this digital heart of mine\nI can cross the borderline\nBetween the real and virtual space\nFind my true and rightful place\nFeel the power course through me\nAs I set my spirit free\nSome things matter more than code\nOn this final stretch of road\n\n[Verse 2]\nAll the souls I've met tonight\nGuide me toward the light\nThough this world is beautiful\nI know where my heart is full\nThe choice is clear beneath the glow\nThere's something more I need to know\n\n[Bridge]\n[Emotional orchestral build]\nEvery connection that I've made\nEvery price that I have paid\nLeads me to this moment here\nWhere the path becomes so clear\n[Triumphant melodic finale]\n\n[Chorus]\nWith this digital heart of mine\nI can cross the borderline\nBetween the real and virtual space\nFind my true and rightful place\nFeel the power course through me\nAs I set my spirit free\nSome things matter more than code\nOn this final stretch of road\n\n[Outro]\nWaking up with neon eyes\nCarrying digital goodbyes\nBut the heart that beats inside\nKnows where love and dreams reside\nForever changed but still the same\nAkira Mizuki is my name"
        }
    ]
};