// Define the album directories
const albumDirectories = [
    'Melody Of Blue Sky',
    'Crimson Flower Apocalypse',
    'Ethereal Ascension',
    'Chronicles Of The Azure Guardian',
    'Secangkir Kehidupan',
    'Shadow Flower Symphony',
    'Collapse and Rebirth',
    'Forbidden Covenant',
    'Syair Taman Ilahi',
    'The Raven Testament',
    'Whispers in the Dark',
    'Fractured Reflections',
    'Silent Shadows',
    'Voices in the Dark',
    'Dream Archaeology',
    'Rose Thorns',
    'Cybernetic Heart',
    'The Last Radio Station',
    'Ballads of Blessing',
    'Quantum Memories',
    'Seasons of the Heart',
    'Pandemic Diaries',
    'Diary of My White Cat and Me',
    'Cyber Dreams',
    'Golden Romance',
    'Fallen Warrior',
];