/**
 * Album Directory Configuration
 *
 * 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: scripts/generate-albums.js
 * Last updated: 2025-11-20T21:45:38.960Z
 *
 * To add new albums:
 * 1. Create album folder in asset/album-name/
 * 2. Add albumData.js to the folder
 * 3. Run: node scripts/generate-albums.js
 * 4. Commit the changes
 *
 * Total albums discovered: 40
 */

const albumDirectories = [
    "Sunset Love",
    "Gothic Princess",
    "Shibuya Student",
    "Urban Sniper",
    "Debug Error",
    "Neon Cityscape",
    "Fragmented Artist",
    "Vaporwave Student",
    "Future Idol",
    "Dark Angel",
    "Cyber Hacker",
    "Neon Dreams",
    "Cyber Warrior",
    "Fallen Warrior",
    "Crimson Warrior",
    "Golden Romance",
    "Cyber Dreams",
    "Ballads of Blessing",
    "Diary of My White Cat and Me",
    "Pandemic Diaries",
    "Seasons of the Heart",
    "Quantum Memories",
    "The Last Radio Station",
    "Cybernetic Heart",
    "Rose Thorns",
    "Dream Archaeology",
    "Voices in the Dark",
    "Silent Shadows",
    "Syair Taman Ilahi",
    "Fractured Reflections",
    "Whispers in the Dark",
    "The Raven Testament",
    "Forbidden Covenant",
    "Collapse and Rebirth",
    "Shadow Flower Symphony",
    "Secangkir Kehidupan",
    "Chronicles Of The Azure Guardian",
    "Ethereal Ascension",
    "Crimson Flower Apocalypse",
    "Melody Of Blue Sky"
];

// Export for module systems (if needed)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = albumDirectories;
}
