// Define album data - making sure it's in the global (window) scope
window.secangkir_kehidupan_data = {
    folder: "Secangkir Kehidupan",
    name: "Secangkir Kehidupan",
    releaseDate: "2025-05-10",
    totalSongs: 5,
    coverArt: "asset/album-name/Secangkir Kehidupan/Art.jpg",
    songsData: [
        {
            title: "Secangkir Rindu",
            style: "Acoustic Pop Ballad, Soft Piano accompaniment, Light percussion, Gentle strings, Warm vocals, Contemporary Malay pop elements, Subtle traditional instrumentation",
            lyrics: "[Verse 1]\nDi balik jendela pagi ini\nSecangkir hangat temani diri\nDalam senyuman tersimpan makna\nMenunggu waktu yang sempurna\n\n[Pre-chorus]\nBiar cahaya mentari\nSinari hati ini\nDalam tenang menanti\n\n[Chorus]\nMungkin esok kau kembali\nMembawa cerita yang kau janji\nSeperti hangatnya pagi\nYang peluk jiwa ini\n\n[Verse 2]\nHijau daun menari di luar\nBagai harapan yang tak melayang\nDalam diamku ada doa\nYang kupanjatkan untuk kita\n\n[Pre-chorus]\nBiar waktu mengalir\nDalam sabar ku berdiri\nMenunggu kau di sini\n\n[Chorus]\nMungkin esok kau kembali\nMembawa cerita yang kau janji\nSeperti hangatnya pagi\nYang peluk jiwa ini\n\n[Bridge]\nDalam setiap tegukan\nTerselip rindu yang dalam\nMenanti waktu Tuhan\nSatukan kita perlahan\n\n[Outro]\nDi balik jendela pagi ini\nKu tunggu sampai nanti\nDengan secangkir rindu ini\nYang tak pernah berhenti"
        },
        {
            title: "Pagi Yang Tenang",
            style: "Contemporary R&B Pop, Soft electronic elements, Modern beats, Smooth vocals, Jazz-influenced chord progressions, Mellow synthesizer pads",
            lyrics: "[Verse 1]\nMentari pagi menyapa lembut\nMelalui kaca jendela waktu\nDalam genggaman cawan berisi\nHarapan baru ku temui\n\n[Pre-chorus]\nDetik-detik berlalu\nDalam damai yang syahdu\nBersama mimpi yang baru\n\n[Chorus]\nDi sini ku berdiri\nMenatap hari yang sunyi\nDengan senyuman ini\nKu sambut yang ku nanti\nOh-whoa-oh\n\n[Verse 2]\nHijabku peluk dengan setia\nSeperti kasih yang tak terlupa\nDalam heningnya pagi ini\nAda cerita yang ku simpan\n\n[Pre-chorus]\nMasa yang mengalir\nBawa damai yang indah\nDalam setiap langkah\n\n[Chorus]\nDi sini ku berdiri\nMenatap hari yang sunyi\nDengan senyuman ini\nKu sambut yang ku nanti\nOh-whoa-oh\n\n[Bridge]\nDalam setiap tegukan hangat\nAda kisah yang ingin kusampaikan\nDalam setiap hembusan nafas\nAda syukur yang tak terhingga\n\n[Pre-chorus]\nBiar waktu berbisik\nTentang indahnya hari ini\nYang tak kan terganti\n\n[Chorus]\nDi sini ku berdiri\nMenatap hari yang sunyi\nDengan senyuman ini\nKu sambut yang ku nanti\n\n[Outro]\nDalam damainya pagi\nKu temukan arti\nTentang indahnya hidup ini\nYang Tuhan beri\n(Oh-whoa-oh)"
        },
        {
            title: "Bisikan Cahaya (Whispers of Light)",
            style: "Alternative Folk-Pop fusion, Traditional Gamelan elements, Modern indie pop production, Acoustic guitar base, Traditional Malay percussion (kompang/rebana), Ethereal vocal harmonies",
            lyrics: "[Verse 1]\nDari balik tirai sutera\nCahaya menari bersama\nDebu-debu berkilauan\nDalam secawan harapan\n\n[Pre-chorus]\nOhh... dalam renungan biru\nTersimpan sejuta makna\nYang tak terungkap\n\n[Chorus]\nBiarkan aku mengalir\nSeperti sinar pagi ini\nDalam damai yang sunyi\nMendakap setiap mimpi\n(Dalam setiap mimpi)\n\n[Verse 2]\nTudung setia memeluk rapi\nBagai awan di langit tinggi\nWaktu mengalir perlahan\nDalam tawa yang tersembunyi\n\n[Pre-chorus]\nOhh... dalam heningnya pagi\nAda kisah tersendiri\nYang ku nikmati\n\n[Chorus]\nBiarkan aku mengalir\nSeperti sinar pagi ini\nDalam damai yang sunyi\nMendakap setiap mimpi\n(Dalam setiap mimpi)\n\n[Bridge]\nDi sini... (Di sini)\nKu temui erti\nTentang indahnya sunyi\nYang memenuhi\nDi sini... (Di sini)\nDalam hangatnya pagi\nAda kisah yang abadi\nYang ku hayati\n\n[Post-Bridge]\nOoo... dalam diamku\nAda syukur yang mengalir\nOoo... dalam nadiku\nAda damai yang berbisik\n\n[Chorus]\nBiarkan aku mengalir\nSeperti sinar pagi ini\nDalam damai yang sunyi\nMendakap setiap mimpi\n\n[Outro]\nBagai cahaya pagi\nYang menyapa lembut hati\nDalam secawan kehidupan\nYang tak terganti\n(Yang tak terganti...)"
        },
        {
            title: "Senyuman Pagi (Morning Smile)",
            style: "Neo-Soul Malay Pop, Jazz-influenced chords, Smooth R&B beats, Traditional Malay flute (seruling) accents, Modern bedroom pop production, Gentle electronic elements",
            lyrics: "[Verse 1]\nDalam sinaran pagi\nBerjuta makna berseri\nCermin memantul bayangan\nSenyuman yang tak hilang\nSeruling pagi berbisik\nTentang kisah yang cantik\n\n[Pre-chorus]\nMmmm... dalam genggaman ini\nAda rahsia yang kusimpani\nYang hanya aku mengerti\n\n[Chorus]\nBukan kebetulan\nSetiap detik yang Tuhan berikan\nBukan sementara\nSetiap sinar yang menyapa dalam kehidupan\n(Oh-oh dalam kehidupan)\n\n[Verse 2]\nHijau daun di luar\nSeperti harapan mekar\nDalam tenangnya waktu\nAda kisah yang malu\nTersipu dalam senyum\nYang tak pernah terpendam\n\n[Pre-chorus]\nMmmm... dalam lembutnya pagi ini\nAda makna yang kucari\nYang hanya hatiku mengerti\n\n[Chorus]\nBukan kebetulan\nSetiap detik yang Tuhan berikan\nBukan sementara\nSetiap sinar yang menyapa dalam kehidupan\n(Oh-oh dalam kehidupan)\n\n[Bridge]\nDi sini... dalam damainya\nKutemui erti cinta\nYang sederhana\nNamun sempurna\nDalam setiap tegukan hangat\nAda kisah yang ingin kuungkap\nTentang indahnya kehidupan\nYang tiada batasnya\n\n[Pre-chorus]\nMmmm... dalam bisikan angin pagi\nAda syukur yang mengisi\nSetiap ruang di hati\n\n[Chorus]\nBukan kebetulan\nSetiap detik yang Tuhan berikan\nBukan sementara\nSetiap sinar yang menyapa dalam kehidupan\n\n[Outro]\nDalam senyuman pagi\nAda kisah abadi\nYang selalu kusyukuri\nDalam setiap nafas ini\n(Dalam setiap nafas ini...)\n(Oh... dalam setiap nafas ini...)"
        },
        {
            title: "Warna Kasih (Colors of Love)",
            style: "Alternative Nusantara Pop, Ethereal Electronic elements, Traditional Ghazal influences, Modern Lo-fi beats, Ambient sounds, Classical Malay strings (Rebab), Contemporary indie production",
            lyrics: "[Verse 1]\nDi antara warna pagi\nMenari bayang-bayang mimpi\nSeperti lukisan yang hidup\nDalam bingkai jendela waktu\n(Dalam bingkai waktu...)\n\n[Pre-chorus]\nBila sunyi berbisik\nDalam secawan kehangatan\nKu temui diri\nDalam keindahan\n\n[Chorus]\nMengalirlah seperti cahaya\nYang lembut menyentuh jiwa\nDalam tenangnya suasana\nKu temui makna\n(Ku temui makna cinta)\n\n[Verse 2]\nTudungku memeluk rasa\nBagai awan putih di sana\nDalam biru mataku ada\nCerita yang tak terkata\n(Yang tak terkata...)\n\n[Pre-chorus]\nBila angin menyapa\nMembawa aroma kenangan\nKu tutup mata\nRasakan kedamaian\n\n[Chorus]\nMengalirlah seperti cahaya\nYang lembut menyentuh jiwa\nDalam tenangnya suasana\nKu temui makna\n(Ku temui makna cinta)\n\n[Bridge]\nDalam setiap warna\nAda kisah berbeza\nYang mengajar erti\nTentang cinta ini\nSetiap hembusan nafas\nMembawa maksud yang khas\nDalam diamku ada\nSyukur yang tak terhingga\n\n[Spoken Word/Melodic]\nDalam keheningan pagi\nKu mengerti erti kehidupan\nYang indah ini...\n\n[Chorus]\nMengalirlah seperti cahaya\nYang lembut menyentuh jiwa\nDalam tenangnya suasana\nKu temui makna\n\n[Outro]\nBiarkan waktu mengalir\nSeperti warna yang berseri\nDalam damai yang abadi\nYang Tuhan beri\n(Yang Tuhan beri...)\n(Dalam damai yang abadi...)"
        }
    ]
};