// Define album data - making sure it's in the global (window) scope
window.the_last_radio_station_data = {
    folder: "The Last Radio Station",
    name: "The Last Radio Station",
    releaseDate: "2025-03-30",
    totalSongs: 7,
    coverArt: "asset/album-name/The Last Radio Station/Art.jpg",
    songsData: [
        {
            title: "Dead Air",
            style: "Atmospheric electronic, static-laden textures, sparse piano notes, subtle radio frequency effects, melancholic synth pads, isolated percussion, tense build-up, emotional electronic with post-apocalyptic ambience",
            lyrics: "[Verse 1]\nStatic fills the empty airwaves\nWhere voices used to be\nI turn the dial in desperate search\nFor someone else like me\nThe world went quiet yesterday\nOr was it years ago?\nTime blurs when you're the only one\nWith memories to show\n\n[Pre-Chorus]\nI don't know if anyone's listening\nI don't know if words still matter\nBut I'll speak into the void\nHoping someone's there\n\n[Chorus]\nDead air, dead air\nI'm breaking through the silence\nDead air, dead air\nA voice in the darkness\nIf anyone can hear me now\nI'm still alive somehow\nBroadcasting hope through dead air\nDead air\n\n[Verse 2]\nDust-covered microphone\nFingerprints from before\nI found this station abandoned\nBut the power still runs, for now\nI speak the date and time each day\nThough no one confirms it's right\nIn a world that's holding its breath\nI exhale into the night\n\n[Pre-Chorus]\nI don't know if anyone's listening\nI don't know if words still matter\nBut I'll speak into the void\nHoping someone's there\n\n[Chorus]\nDead air, dead air\nI'm breaking through the silence\nDead air, dead air\nA voice in the darkness\nIf anyone can hear me now\nI'm still alive somehow\nBroadcasting hope through dead air\nDead air\n\n[Bridge]\nMaybe I'm just talking to myself\nEchoes in an empty world\nBut something keeps me pressing this button\nSomething keeps me believing\nThat I'm not alone\n\n[Chorus]\nDead air, dead air\nI'm breaking through the silence\nDead air, dead air\nA voice in the darkness\nIf anyone can hear me now\nI'm still alive somehow\nBroadcasting hope through dead air\nDead air\n\n[Outro]\nThis is The Last Radio Station\nTransmitting on all frequencies\nI am still here\nAre you?"
        },
        {
            title: "Signal Found",
            style: "Progressive electronic with hopeful undertones, echoing radio transmissions, building percussion, cinematic synth swells, emotional vocal processing, digital glitches, future bass drops, melodic chord progressions with radio static elements",
            lyrics: "[Verse 1]\nThree weeks of talking to ghosts\nWords falling into the void\nThen came that crackle of sound\nA voice through the static noise\nShaking hands adjust the dial\nHeart racing, barely breathe\nAfter all this emptiness\nAnother soul I can reach\n\n[Pre-Chorus]\nA transmission from the darkness\nA lifeline through the static\nThe sound of another survivor\nBreaking through the silence\n\n[Chorus]\nSignal found in the wasteland\nI'm not the last one alive\nSignal found through the dead air\nSomeone survived\nYour voice breaks through my solitude\nA lifeline in the night\nSignal found, we're not alone\nWe're not alone\n\n[Verse 2]\nYou speak of others like you\nHuddled around the fire\nSharing static-filled broadcasts\nMy words travel through wire\nCoordinates exchanged with care\nTrust is a luxury now\nIn a world that's broken apart\nConnection is all that counts\n\n[Pre-Chorus]\nA transmission from the darkness\nA lifeline through the static\nThe sound of another survivor\nBreaking through the silence\n\n[Chorus]\nSignal found in the wasteland\nI'm not the last one alive\nSignal found through the dead air\nSomeone survived\nYour voice breaks through my solitude\nA lifeline in the night\nSignal found, we're not alone\nWe're not alone\n\n[Bridge]\nThrough miles of broken cities\nAcross the scarred landscape\nYour voice reaches me\nProof that humanity remains\nWe may be scattered remnants\nBut we still have our voice\nAnd in this silent world\nThat makes all the difference\n\n[Chorus]\nSignal found in the wasteland\nI'm not the last one alive\nSignal found through the dead air\nSomeone survived\nYour voice breaks through my solitude\nA lifeline in the night\nSignal found, we're not alone\nWe're not alone\n\n[Outro]\nWe're not alone\nSignal found\nWe're not alone"
        },
        {
            title: "Wasteland Chronicles",
            style: "Narrative electronic, ambient storytelling elements, nostalgic piano melodies, distant percussion, atmospheric sound design, emotional synth transitions, melodic drops with wasteland sound effects, documentary-style production",
            lyrics: "[Verse 1]\nGood evening, wasteland\nThis is your host again\nToday I'm sharing stories\nFrom what's left of our world\nMessages from survivors\nHistories we can't forget\nBefore they turn to dust\nLike everything else\n\n[Pre-Chorus]\nThese are the chronicles\nOf those who remain\nVoices in the silence\nMemories through pain\n\n[Chorus]\nWasteland chronicles, echoing through time\nWasteland chronicles, yours and mine\nStories from the ashes, keeping hope alive\nWasteland chronicles, helping us survive\nWasteland chronicles, tales we need to share\nWasteland chronicles, proof that we still care\nThough the world has fallen, we refuse to fade\nWasteland chronicles, history remade\n\n[Verse 2]\nA family in the mountains\nGrowing food in ashen soil\nA teacher with her students\nKeeping knowledge alive\nA doctor with no medicine\nHealing with what remains\nSmall victories each day\nAgainst endless terrain\n\n[Pre-Chorus]\nThese are the chronicles\nOf those who remain\nVoices in the silence\nMemories through pain\n\n[Chorus]\nWasteland chronicles, echoing through time\nWasteland chronicles, yours and mine\nStories from the ashes, keeping hope alive\nWasteland chronicles, helping us survive\nWasteland chronicles, tales we need to share\nWasteland chronicles, proof that we still care\nThough the world has fallen, we refuse to fade\nWasteland chronicles, history remade\n\n[Bridge]\nWe document the present\nTo not forget the past\nWe share our daily struggles\nTo make our courage last\nThough separated by distance\nUnited through these waves\nThe stories of our survival\nAre all that remains\n\n[Chorus]\nWasteland chronicles, echoing through time\nWasteland chronicles, yours and mine\nStories from the ashes, keeping hope alive\nWasteland chronicles, helping us survive\nWasteland chronicles, tales we need to share\nWasteland chronicles, proof that we still care\nThough the world has fallen, we refuse to fade\nWasteland chronicles, history remade\n\n[Outro]\nThis concludes today's broadcast\nKeep your radios close\nYour stories matter\nYour voice matters\nThis is The Last Radio Station\nReminding you you're not alone"
        },
        {
            title: "Radio Tower Defense",
            style: "Tense electronic, aggressive bass drops, defensive percussion patterns, alarm-like synth motifs, threatening atmospheric elements, urgent vocal processing, powerful builds to dramatic drops, vigilant sound design with radio interference",
            lyrics: "[Verse 1]\nStrangers at the perimeter\nI can see them from the tower\nEyes fixed on my sanctuary\nHunger for what I have\nThey want the generator\nThey want the transmitter\nThey want the power I hold\nTo speak across the silence\n\n[Pre-Chorus]\nI've built this place from nothing\nBroadcasting hope to strangers\nWill I become the victim\nOf what I've created?\n\n[Chorus]\nRadio tower defense\nProtecting what matters now\nRadio tower defense\nWon't let them take this down\nThe last voice in the darkness\nThe last thread connecting us\nRadio tower defense\nI'll stand my ground\n\n[Verse 2]\nFingertips on the trigger\nMicrophone in the other hand\nUnsure which has more power\nIn this broken land\nI broadcast my intentions\nWarning shots in the air\nI built this to connect us\nNot to create more fear\n\n[Pre-Chorus]\nI've built this place from nothing\nBroadcasting hope to strangers\nWill I become the victim\nOf what I've created?\n\n[Chorus]\nRadio tower defense\nProtecting what matters now\nRadio tower defense\nWon't let them take this down\nThe last voice in the darkness\nThe last thread connecting us\nRadio tower defense\nI'll stand my ground\n\n[Bridge]\nCan we share this tower?\nCan we share this voice?\nIn a world so fragmented\nMust we fight for every choice?\nThe airwaves belong to no one\nThe signal is for all\nPerhaps in defending this tower\nI've forgotten my call\n\n[Chorus]\nRadio tower defense\nProtecting what matters now\nRadio tower defense\nWon't let them take this down\nThe last voice in the darkness\nThe last thread connecting us\nRadio tower defense\nI'll lower my guard\n\n[Outro]\nThis tower isn't just mine\nThese airwaves belong to us all\nDefending what matters\nMeans remembering why it matters"
        },
        {
            title: "Broadcast Hope",
            style: "Inspirational electronic, uplifting chord progressions, emotional drops, hopeful vocal delivery, anthemic synthesizer leads, building from minimal elements to powerful chorus, united humanity themes in production with radio transmission textures",
            lyrics: "[Verse 1]\nJust a voice through the speaker\nJust words through static and noise\nBut I've seen what they can do\nHow they light up the eyes\nOf those who thought they were forgotten\nOf those who'd lost their way\nSomething as simple as knowing\nSomeone else made it through another day\n\n[Pre-Chorus]\nSo I'll keep talking\nThough my voice gets hoarse\nI'll keep broadcasting\nCharts for this new course\n\n[Chorus]\nBroadcast hope across the wasteland\nBeacon in the darkest night\nBroadcast hope to those who wander\nGuidance through their fight\nThese words may seem so fragile\nBut they build bridges through the sky\nBroadcast hope with every signal\nReason to survive\n\n[Verse 2]\nWeather patterns and safe routes\nMedical advice when doctors are gone\nBedtime stories for the children\nMusic to carry them along\nThe locations of clean water\nWarnings of dangers ahead\nIt's not just information\nIt's proof we haven't given up yet\n\n[Pre-Chorus]\nSo I'll keep talking\nThough my voice gets hoarse\nI'll keep broadcasting\nCharts for this new course\n\n[Chorus]\nBroadcast hope across the wasteland\nBeacon in the darkest night\nBroadcast hope to those who wander\nGuidance through their fight\nThese words may seem so fragile\nBut they build bridges through the sky\nBroadcast hope with every signal\nReason to survive\n\n[Bridge]\nWhen all other institutions failed\nWhen governments crumbled to dust\nThe simple act of communication\nBecame our sacred trust\nA community built on airwaves\nInvented from the void\nProving that humanity's spirit\nCannot be destroyed\n\n[Chorus]\nBroadcast hope across the wasteland\nBeacon in the darkest night\nBroadcast hope to those who wander\nGuidance through their fight\nThese words may seem so fragile\nBut they build bridges through the sky\nBroadcast hope with every signal\nReason to survive\n\n[Outro]\nThis is The Last Radio Station\nBroadcasting hope\nWherever you are\nYou are not alone"
        },
        {
            title: "Distant Signals",
            style: "Mysterious electronic, otherworldly frequency effects, searching synth patterns, distant vocal echoes, discovery-themed sound design, progressive builds, sparse to full arrangements, expansive atmospheric elements with radio scanning sounds",
            lyrics: "[Verse 1]\nLate night at the console\nTuning through empty bands\nWhen something caught my attention\nFaint signals from distant lands\nNot just the survivors I know\nNot just familiar codes\nSomething structured and rhythmic\nFrom somewhere far beyond\n\n[Pre-Chorus]\nDistant signals calling\nVoices I've never heard\nDistant signals showing\nWe're not the only ones\n\n[Chorus]\nDistant signals breaking through\nFrom places I can't see\nDistant signals reaching out\nMore broadcasters like me\nThe world is bigger than I thought\nThe hope is spreading wide\nDistant signals in the night\nRebuilding what's alive\n\n[Verse 2]\nAnother radio station\nA different kind of show\nAccents I barely recognize\nBut intentions I clearly know\nThey speak of their own struggles\nTheir victories and fears\nA mirror to our existence\nAcross the hemisphere\n\n[Pre-Chorus]\nDistant signals calling\nVoices I've never heard\nDistant signals showing\nWe're not the only ones\n\n[Chorus]\nDistant signals breaking through\nFrom places I can't see\nDistant signals reaching out\nMore broadcasters like me\nThe world is bigger than I thought\nThe hope is spreading wide\nDistant signals in the night\nRebuilding what's alive\n\n[Bridge]\nWe've been so isolated\nEach thinking we're alone\nBut across the broken world\nOthers have found their microphone\nDifferent languages and stories\nSame purpose in the end\nTo connect the fragments\nTo help humanity transcend\n\n[Chorus]\nDistant signals breaking through\nFrom places I can't see\nDistant signals reaching out\nMore broadcasters like me\nThe world is bigger than I thought\nThe hope is spreading wide\nDistant signals in the night\nRebuilding what's alive\n\n[Outro]\nI'm receiving your transmission\nI hear you through the static\nWe are not alone\nWe are finding each other"
        },
        {
            title: "New Frequency",
            style: "Triumphant electronic finale, uplifting drops, community-themed chord progressions, collaborative vocal elements, forward-looking synthesizer arrangements, dawn-themed sound design, conclusive yet opening-to-future production with radio frequency switchover effects",
            lyrics: "[Verse 1]\nCoordinating broadcasts\nSchedules shared across the waves\nA network slowly forming\nFrom our isolated days\nYour station and my station\nAnd dozens more we've found\nJoining on a new frequency\nTo amplify our sound\n\n[Pre-Chorus]\nFinding each other\nAcross the distance\nStronger together\nA new resistance\n\n[Chorus]\nNew frequency uniting us all\nNew frequency rising from the fall\nThe scattered pieces finding their place\nA second chance for the human race\nNew frequency breaking isolation\nNew frequency building a foundation\nFrom single voices to a chorus strong\nA new world where we all belong\n\n[Verse 2]\nSharing knowledge freely\nWhat works and what has failed\nCoordinating movements\nPlotting paths through the veil\nThe children born post-silence\nWill grow in a connected world\nRebuilding from the ashes\nWith wisdom dearly earned\n\n[Pre-Chorus]\nFinding each other\nAcross the distance\nStronger together\nA new resistance\n\n[Chorus]\nNew frequency uniting us all\nNew frequency rising from the fall\nThe scattered pieces finding their place\nA second chance for the human race\nNew frequency breaking isolation\nNew frequency building a foundation\nFrom single voices to a chorus strong\nA new world where we all belong\n\n[Bridge]\nWe broadcast from the ruins\nTo build something new\nNot to restore what was lost\nBut to create what is true\nA network of humanity\nNot bound by old mistakes\nOn this new frequency\nA better world awakes\n\n[Chorus]\nNew frequency uniting us all\nNew frequency rising from the fall\nThe scattered pieces finding their place\nA second chance for the human race\nNew frequency breaking isolation\nNew frequency building a foundation\nFrom single voices to a chorus strong\nA new world where we all belong\n\n[Outro]\nThis is not just The Last Radio Station anymore\nThis is the first of many\nThis is our new beginning\nTune in, reach out, rebuild\nWe're waiting for you\nOn the new frequency"
        }
    ]
};