#!/usr/bin/env node

/**
 * Automatic Album Discovery Script
 * Scans asset/album-name/ directory and generates asset/js/album-data.js
 *
 * Usage: node scripts/generate-albums.js
 */

const fs = require('fs');
const path = require('path');

// Configuration
const ALBUM_DIR = path.join(__dirname, '..', 'asset', 'album-name');
const OUTPUT_FILE = path.join(__dirname, '..', 'asset', 'js', 'album-data.js');

console.log('🎵 Kiyoraka Ken Music Album - Auto-Discovery Script\n');

try {
    // Check if album directory exists
    if (!fs.existsSync(ALBUM_DIR)) {
        console.error(`❌ Error: Album directory not found: ${ALBUM_DIR}`);
        process.exit(1);
    }

    // Read all items in the album directory
    const items = fs.readdirSync(ALBUM_DIR);

    // Filter for directories only, exclude hidden files
    const albumFolders = items.filter(item => {
        const itemPath = path.join(ALBUM_DIR, item);
        const stats = fs.statSync(itemPath);
        return stats.isDirectory() && !item.startsWith('.');
    });

    // Get folder stats for sorting by modification time
    const foldersWithStats = albumFolders.map(folder => {
        const folderPath = path.join(ALBUM_DIR, folder);
        const stats = fs.statSync(folderPath);

        // Check if albumData.js exists
        const albumDataPath = path.join(folderPath, 'albumData.js');
        const hasAlbumData = fs.existsSync(albumDataPath);

        return {
            name: folder,
            mtime: stats.mtime,
            hasAlbumData
        };
    });

    // Sort by modification time (newest first) - matches your creative workflow
    foldersWithStats.sort((a, b) => b.mtime - a.mtime);

    // Extract folder names in sorted order
    const sortedAlbums = foldersWithStats.map(f => f.name);

    // Warn about albums without albumData.js
    const missingData = foldersWithStats.filter(f => !f.hasAlbumData);
    if (missingData.length > 0) {
        console.warn('⚠️  Warning: The following albums are missing albumData.js:');
        missingData.forEach(f => console.warn(`   - ${f.name}`));
        console.log();
    }

    // Generate the album-data.js content
    const fileContent = `/**
 * Album Directory Configuration
 *
 * 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: scripts/generate-albums.js
 * Last updated: ${new Date().toISOString()}
 *
 * To add new albums:
 * 1. Create album folder in asset/album-name/
 * 2. Add albumData.js to the folder
 * 3. Run: node scripts/generate-albums.js
 * 4. Commit the changes
 *
 * Total albums discovered: ${sortedAlbums.length}
 */

const albumDirectories = ${JSON.stringify(sortedAlbums, null, 4)};

// Export for module systems (if needed)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = albumDirectories;
}
`;

    // Write the file
    fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf8');

    // Success report
    console.log(`✅ Successfully generated album-data.js`);
    console.log(`📁 Discovered ${sortedAlbums.length} albums:`);
    console.log();

    sortedAlbums.forEach((album, index) => {
        const hasData = foldersWithStats[index].hasAlbumData ? '✓' : '✗';
        console.log(`   ${hasData} ${album}`);
    });

    console.log();
    console.log(`📝 Output: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
    console.log('🎉 Auto-discovery complete!\n');

} catch (error) {
    console.error('❌ Error during album discovery:', error.message);
    process.exit(1);
}
