// Define album data - making sure it's in the global (window) scope
window.quantum_memories_data = {
    folder: "Quantum Memories",
    name: "Quantum Memories",
    releaseDate: "2025-04-11",
    totalSongs: 7,
    coverArt: "asset/album-name/Quantum Memories/Art.jpg",
    songsData: [
        {
            title: "Waveform Collapse",
            style: "Ambient electronic with quantum noise elements, layered synthesizers, glitchy percussion that resolves into structured beats, ethereal vocal processing, with occasional dynamic bass drops and soaring melodic moments that create contrast between meditative states and moments of intense energy",
            lyrics: "[Intro]\nInfinite possibilities\nSuspended in potential\nWaiting for the moment\nOf decision...\n\n[Verse 1]\nFloating in a sea of maybe\nAll futures overlapping\nEvery choice existing\nIn a state of quantum grace\nUntil observation breaks the spell\nAnd maybes turn to must be\nPossibilities unfold their wings\nAnd take a solid shape\n\n[Pre-Chorus]\nThe universe holds its breath\nAs probability condenses\nFrom many to the one\n\n[Chorus]\nWaveform collapse\nThe moment of becoming\nWaveform collapse\nWhen many paths turn singular\nWaveform collapse\nAs quantum wings unfold\nInto this reality\nThis moment, this choice, this life\n\n[Verse 2]\nThe cat in the box is living and dead\nUntil we lift the lid\nOur lives a blur of could-be paths\nUntil we make decision\nThe quantum state resolving\nLike azure wings in flight\nReaching through uncertainty\nTo grasp what we call real\n\n[Chorus]\nWaveform collapse\nThe moment of becoming\nWaveform collapse\nWhen many paths turn singular\nWaveform collapse\nAs quantum wings unfold\nInto this reality\nThis moment, this choice, this life\n\n[Outro]\nThe wave becomes a particle\nThe ghost becomes a shell\nPotential crystallizes\nElectronic wings take flight\nThrough quantum atmospheres unknown"
        },
        {
            title: "The Lives Not Lived",
            style: "Nostalgic electronic pop with retro synth elements and bittersweet chord progressions, enhanced with powerful future bass choruses, dynamic percussion breaks, and cinematic swells that create emotional peaks while maintaining the reflective core feeling",
            lyrics: "[Verse 1]\nIn another timeline I became an astronaut\nExploring distant stars while Earth became a memory\nIn another world I never left my hometown\nRaised a family where my parents raised me\nAll these lives not lived still haunt me\nGhosts of paths I might have known\n\n[Pre-Chorus]\nDo they miss me, these other selves?\nDo they wonder about the road not traveled?\nDo their quantum wings soar higher\nThrough skies I'll never know?\n\n[Chorus]\nThe lives not lived, shimmering like mirages\nThe lives not lived, just one decision away\nThe lives not lived, like phantom wings unfurled\nThe lives not lived, where other versions of me stay\nAre they looking back at me?\nAcross the quantum sea?\nWondering about the life I lead?\n\n[Verse 2]\nIn another timeline I said \"yes\" instead of \"no\"\nAnd everything that followed took a different shape\nIn another world I zigged instead of zagged\nWatched my wings spread wide through different skies\nAll these lives not lived still echo\nReflections in a quantum sea\n\n[Chorus]\nThe lives not lived, shimmering like mirages\nThe lives not lived, just one decision away\nThe lives not lived, like phantom wings unfurled\nThe lives not lived, where other versions of me stay\nAre they looking back at me?\nAcross the quantum sea?\nWondering about the life I lead?\n\n[Outro]\nSomewhere I'm still becoming\nWings spread through electric skies\nLives unfolding without me\nForever just beyond my reach"
        },
        {
            title: "Schrödinger's Heart",
            style: "Indie electronic with dual-mood composition alternating between introspective, melancholic sections and euphoric, hopeful releases, featuring quantum beats that transform between structured and chaotic, with dramatic dynamic shifts and occasional cathartic bass drops",
            lyrics: "[Verse 1]\nI loved you and I loved you not\nI stayed and yet I walked away\nI felt everything intensely\nWhile feeling nothing at all\nMy heart trapped in a quantum box\nBoth alive with joy and dead with pain\nLike wings folded and expanded\nAll states at once contained\n\n[Pre-Chorus]\nSchrödinger's heart\nBeating for you and not for you\nUntil observation forces\nThese quantum wings to choose their flight\n\n[Chorus]\nI'm in two states simultaneously\nLoving you and letting you go\nSchrödinger's heart inside my chest\nContradictions all I know\nBoth moving on and standing still\nBoth forgetting and holding tight\nThese wings of paradox unfold\nUntil emotions collapse into light\n\n[Verse 2]\nI'm certain and I'm full of doubt\nI'm healing while the wound still bleeds\nMy heart exists in superposition\nHope and despair occupy one space\nLike quantum wings both folded and spread\nAcross realities undefined\n\n[Chorus]\nI'm in two states simultaneously\nLoving you and letting you go\nSchrödinger's heart inside my chest\nContradictions all I know\nBoth moving on and standing still\nBoth forgetting and holding tight\nThese wings of paradox unfold\nUntil emotions collapse into light\n\n[Outro]\nUntil I observe the state of my heart\nIt remains both loving and free\nSpread across quantum uncertainty\nThese wings caught between worlds"
        },
        {
            title: "Multiverse Highway",
            style: "Driving electronic rock with branching musical motifs and road trip atmosphere, featuring powerful electronic buildups, stadium-worthy drops, highway rhythm patterns that accelerate and decelerate, and exhilarating moments that capture the thrill of infinite possibilities",
            lyrics: "[Verse 1]\nCruising down the multiverse highway\nInfinite lanes stretching out before me\nEach exit leads to another life\nEach turn a new reality\nAt every junction, the universe splits\nCreating paths I'll never see\nThese quantum wings guide my journey\nThrough lanes of possibility\n\n[Pre-Chorus]\nEvery choice is an exit ramp\nEvery decision a fork in time\nSpread these wings and take your flight\nThrough endless skies of might-have-been\n\n[Chorus]\nMultiverse highway, endless roads\nMultiverse highway, where all possibilities unfold\nSome paths lead to glory, some lead to pain\nThese wings of choice soar through electric skies\nMultiverse highway, infinite lanes\nEvery choice we make, creates another way\n\n[Verse 2]\nA million versions of myself\nAll driving their separate cars\nAll thinking they chose the only road\nAll spreading different wings\nEach a different shade of me\nAll gazing at different stars\n\n[Chorus]\nMultiverse highway, endless roads\nMultiverse highway, where all possibilities unfold\nSome paths lead to glory, some lead to pain\nThese wings of choice soar through electric skies\nMultiverse highway, infinite lanes\nEvery choice we make, creates another way\n\n[Outro]\nI'll keep driving my particular lane\nThese quantum wings spread wide\nWondering about the exits I passed\nSomewhere, other versions of me\nAre flying through different skies"
        },
        {
            title: "Quantum Entanglement",
            style: "Ethereal duet with perfectly synchronized male and female vocals and mirroring musical phrases, enhanced with powerful orchestral swells, electronic crescendos, and moments of transcendent bass that physically express the unbreakable bond between particles",
            lyrics: "[Verse 1]\nSeparated by a thousand miles\nYet I feel your every breath\nWhen your heart skips, mine follows suit\nA connection that defies death\nLike quantum wings beating in sync\nAcross impossible distance\nNo signal passes between us\nYet somehow we remain connected\n\n[Pre-Chorus]\nTwo particles, once united\nRemain linked across all space\nLike wings that mirror each other's flight\nNo matter the time, no matter the place\n\n[Chorus]\nQuantum entanglement, spooky action at a distance\nQuantum entanglement, defying space and time\nOur souls intertwined beyond physical existence\nWhat happens to you, happens to me\nThese entangled wings in perfect harmony\nA cosmic connection, impossible to sever\n\n[Verse 2]\nI dream your dreams before you tell me\nI feel your pain before you call\nYou know my thoughts before I speak them\nAs if there's no distance at all\nOur quantum wings beat as one\nAcross the void between stars\n\n[Chorus]\nQuantum entanglement, spooky action at a distance\nQuantum entanglement, defying space and time\nOur souls intertwined beyond physical existence\nWhat happens to you, happens to me\nThese entangled wings in perfect harmony\nA cosmic connection, impossible to sever\n\n[Outro]\nI'll feel you always\nAcross space and time\nThese quantum wings entangled\nYour heart tied to mine"
        },
        {
            title: "Observer Effect",
            style: "Experimental electronic with reality-shifting production and perception-altering synthesizers, punctuated with moments of dramatic clarity, powerful drops that represent observation crystallizing reality, and dynamic contrasts between uncertain and defined sonic states",
            lyrics: "[Verse 1]\nIs the tree still there when no one looks?\nDoes the moon exist when clouds conceal?\nDoes reality spread its wings\nWhen there's no one there to see?\nThe quantum world suggests the strangest truth:\nReality depends on observation\nThe act of looking changes what we see\nConsciousness creates manifestation\n\n[Pre-Chorus]\nThe observer and the observed\nLocked in cosmic dance\nAs quantum wings unfold\nIn response to conscious glance\n\n[Chorus]\nThe observer effect, reality shifts under my gaze\nThe observer effect, perception shapes our ways\nLike wings that form from possibility\nWhen consciousness decides what form to see\nNothing exists in definite form\nUntil we choose which wings unfold\n\n[Verse 2]\nElectrons act like waves until we look\nThen suddenly behave like points in space\nPerhaps our lives work just the same way\nPotential wings until we choose their shape\nThe very act of living consciously\nCreates the world that's meant to be\n\n[Chorus]\nThe observer effect, reality shifts under my gaze\nThe observer effect, perception shapes our ways\nLike wings that form from possibility\nWhen consciousness decides what form to see\nNothing exists in definite form\nUntil we choose which wings unfold\n\n[Outro]\nI'm looking at the world\nThe world looking back\nQuantum wings materializing\nIn response to conscious act"
        },
        {
            title: "Superposition",
            style: "Harmonically complex electronic with peaceful resolution and multiple musical layers that eventually synchronize, building to powerful euphoric moments that represent the liberation of accepting all possible states, with rich textural development and transcendent climaxes",
            lyrics: "[Verse 1]\nAll possibilities exist at once\nEvery contradiction simultaneously true\nI am particle and wave, certainty and doubt\nThese quantum wings both folded and spread\nThe quantum world accepts what we cannot:\nThat opposites need not be resolved\nThat paradox is natural state\nAll wings can fly at once\n\n[Pre-Chorus]\nIn superposition I find peace\nIn both/and, not either/or\nThese quantum wings embrace all forms\nInfinite paths through every door\n\n[Chorus]\nSuperposition, all possibilities embraced\nSuperposition, no potential goes to waste\nI am all versions of myself\nMy wings spread through every sky\nSuperposition, freedom in quantum truth\nEvery reality simultaneously alive\n\n[Verse 2]\nThe anxiety of choosing fades away\nWhen I accept all paths as valid and real\nThe FOMO dissipates like morning fog\nWhen all my wings fly at once\nFor somewhere in the quantum multiverse\nEvery mountain I might climb, I climb\n\n[Chorus]\nSuperposition, all possibilities embraced\nSuperposition, no potential goes to waste\nI am all versions of myself\nMy wings spread through every sky\nSuperposition, freedom in quantum truth\nEvery reality simultaneously alive\n\n[Outro]\nThe multiverse contains it all\nEvery wing configuration possible\nEvery path is traveled somewhere\nAnd in this truth I find my rest\nMy quantum wings embracing all"
        }
    ]
};