// Define album data - making sure it's in the global (window) scope
window.quantum_memories_data = {
    folder: "Quantum Memories",
    name: "Quantum Memories",
    releaseDate: "2025-04-11",
    totalSongs: 7,
    coverArt: "asset/album-name/Quantum Memories/Art.jpg",
    songsData: [
        {
            title: "Waveform Collapse",
            style: "Ambient electronic with quantum noise elements, layered synthesizers, glitchy percussion that resolves into structured beats, ethereal vocal processing, crystallization sound effects, and gradual sonic coalescence",
            lyrics: "[Intro]\nInfinite possibilities\nSuspended in potential\nWaiting for the moment\nOf decision...\n\n[Verse 1]\nFloating in a sea of maybe\nAll futures overlapping\nEvery choice existing\nIn a state of quantum grace\nUntil the moment of observation\nWhen waveforms start collapsing\nAnd maybes turn to must be\nPossibilities erased\n\n[Pre-Chorus]\nThe universe holds its breath\nAs probability condenses\nFrom many to the one\n\n[Chorus]\nWaveform collapse\nThe moment of becoming\nWaveform collapse\nWhen many paths turn singular\nWaveform collapse\nInfinity distilling\nInto this reality\nThis moment, this choice, this life\n\n[Verse 2]\nThe cat in the box is living and dead\nUntil we lift the lid\nThe electron's position undefined\nUntil measured with precision\nOur lives a blur of could-be paths\nUntil we make decision\nThe quantum state resolving\nAs we walk the chosen way\n\n[Pre-Chorus]\nThe universe holds its breath\nAs probability condenses\nFrom many to the one\n\n[Chorus]\nWaveform collapse\nThe moment of becoming\nWaveform collapse\nWhen many paths turn singular\nWaveform collapse\nInfinity distilling\nInto this reality\nThis moment, this choice, this life\n\n[Bridge]\nWhat if every decision\nCreates a branch in time?\nWhat if every waveform\nNever truly dies?\nBut flourishes elsewhere\nIn worlds we cannot see\nEvery path not taken\nStill unfolding endlessly\n\n[Chorus]\nWaveform collapse\nThe moment of becoming\nWaveform collapse\nWhen many paths turn singular\nWaveform collapse\nInfinity distilling\nInto this reality\nThis moment, this choice, this life\n\n[Outro]\nThe wave becomes a particle\nThe ghost becomes a shell\nPotential crystallizes\nInto what we call real"
        },
        {
            title: "The Lives Not Lived",
            style: "Nostalgic electronic pop with retro synth elements, bittersweet chord progressions, dreamy vocals, alternative timeline sound design, 80s-inspired instrumentation with modern production, and contemplative melodic hooks",
            lyrics: "[Verse 1]\nIn another timeline I became an astronaut\nExploring distant stars while Earth became a memory\nIn another world I never left my hometown\nRaised a family where my parents raised me\nIn another life I'm famous beyond measure\nIn another I live quietly, unknown\nAll these lives not lived still haunt me\nGhosts of paths I might have known\n\n[Pre-Chorus]\nDo they miss me, these other selves?\nDo they wonder about the road not traveled?\nAre they happy with the choices made?\nOr do they dream of me as I dream of them?\n\n[Chorus]\nThe lives not lived, shimmering like mirages\nThe lives not lived, just one decision away\nThe lives not lived, in parallel dimensions\nThe lives not lived, where other versions of me stay\nAre they looking back at me?\nAcross the quantum sea?\nWondering about the life I lead?\n\n[Verse 2]\nIn another timeline I said \"yes\" instead of \"no\"\nAnd everything that followed took a different shape\nIn another world I zigged instead of zagged\nMade the safe choice, not the brave escape\nIn another life I found a different purpose\nIn another I pursued the same dream differently\nAll these lives not lived still echo\nReflections in a quantum sea\n\n[Pre-Chorus]\nDo they miss me, these other selves?\nDo they wonder about the road not traveled?\nAre they happy with the choices made?\nOr do they dream of me as I dream of them?\n\n[Chorus]\nThe lives not lived, shimmering like mirages\nThe lives not lived, just one decision away\nThe lives not lived, in parallel dimensions\nThe lives not lived, where other versions of me stay\nAre they looking back at me?\nAcross the quantum sea?\nWondering about the life I lead?\n\n[Bridge]\nCountless versions of myself\nSpread across the multiverse\nSome happier, some sadder\nSome better and some worse\nBut all of them authentic\nAll of them still me\nDifferent permutations\nOf who I'm meant to be\n\n[Chorus]\nThe lives not lived, shimmering like mirages\nThe lives not lived, just one decision away\nThe lives not lived, in parallel dimensions\nThe lives not lived, where other versions of me stay\nAre they looking back at me?\nAcross the quantum sea?\nWondering about the life I lead?\n\n[Outro]\nSomewhere I'm still becoming\nAll the things I might have been\nLives unfolding without me\nForever just beyond my reach"
        },
        {
            title: "Schrödinger's Heart",
            style: "Indie electronic with dual-mood composition, oscillating between melancholic and hopeful sections, quantum beats that alternate between structured and chaotic, emotionally conflicted vocals, and paradoxical lyrical delivery",
            lyrics: "[Verse 1]\nI loved you and I loved you not\nI stayed and yet I walked away\nI felt everything intensely\nWhile feeling nothing at all\nMy heart trapped in a quantum box\nBoth alive with joy and dead with pain\nCan both states exist together?\nUntil the moment you call\n\n[Pre-Chorus]\nSchrödinger's heart\nBeating for you and not for you\nUntil observation forces\nThe waveform to resolve\n\n[Chorus]\nI'm in two states simultaneously\nLoving you and letting you go\nSchrödinger's heart inside my chest\nContradictions all I know\nBoth moving on and standing still\nBoth forgetting and holding tight\nSchrödinger's heart, a paradox\nUntil emotions collapse into light\n\n[Verse 2]\nI'm certain and I'm full of doubt\nI'm healing while the wound still bleeds\nI'm speaking truth and telling lies\nI'm fulfilled yet incomplete\nMy heart exists in superposition\nHope and despair occupy one space\nCan feelings be so contradictory?\nYet still maintain their grace\n\n[Pre-Chorus]\nSchrödinger's heart\nBeating for you and not for you\nUntil observation forces\nThe waveform to resolve\n\n[Chorus]\nI'm in two states simultaneously\nLoving you and letting you go\nSchrödinger's heart inside my chest\nContradictions all I know\nBoth moving on and standing still\nBoth forgetting and holding tight\nSchrödinger's heart, a paradox\nUntil emotions collapse into light\n\n[Bridge]\nWhen I see you again\nWill the waveform finally collapse?\nWill my heart choose its state?\nOr remain forever trapped\nBetween what was and what could be\nBetween loving and letting go\nBetween emotional certainty\nAnd the quantum unknowable\n\n[Chorus]\nI'm in two states simultaneously\nLoving you and letting you go\nSchrödinger's heart inside my chest\nContradictions all I know\nBoth moving on and standing still\nBoth forgetting and holding tight\nSchrödinger's heart, a paradox\nUntil emotions collapse into light\n\n[Outro]\nUntil I observe the state of my heart\nIt remains both loving and free\nLiving in quantum uncertainty\nWhich is the real me?"
        },
        {
            title: "Multiverse Highway",
            style: "Driving electronic rock with branching musical motifs, road trip atmosphere, multiple alternate melodic paths that converge and diverge, decision-point breaks, journey-themed instrumentation, and highway rhythm patterns",
            lyrics: "[Verse 1]\nCruising down the multiverse highway\nInfinite lanes stretching out before me\nEach exit leads to another life\nEach turn a new reality\nAt every junction, the universe splits\nCreating paths I'll never see\nIn one direction lies fortune and fame\nIn another, sweet simplicity\n\n[Pre-Chorus]\nEvery choice is an exit ramp\nEvery decision a fork in time\nThe multiverse highway never ends\nJust branches eternally\n\n[Chorus]\nMultiverse highway, endless roads\nMultiverse highway, where all possibilities unfold\nSome paths lead to glory, some lead to pain\nSome to love lost, some to love gained\nMultiverse highway, infinite lanes\nEvery choice we make, creates another way\n\n[Verse 2]\nIn one lane I swerve to miss the accident\nIn another I wasn't so lucky\nIn one reality I took that job offer\nIn another I chose to be free\nA million versions of myself\nAll driving their separate cars\nAll thinking they chose the only road\nAll gazing at different stars\n\n[Pre-Chorus]\nEvery choice is an exit ramp\nEvery decision a fork in time\nThe multiverse highway never ends\nJust branches eternally\n\n[Chorus]\nMultiverse highway, endless roads\nMultiverse highway, where all possibilities unfold\nSome paths lead to glory, some lead to pain\nSome to love lost, some to love gained\nMultiverse highway, infinite lanes\nEvery choice we make, creates another way\n\n[Bridge]\nNo wrong turns when every path exists\nNo road not taken when all roads are traveled\nSomewhere I always make the other choice\nSomewhere the knot is always unraveled\nWhat comfort in knowing nothing's truly lost\nWhat terror in endless possibility\nThe multiverse highway has no final destination\nJust infinite journeys of you and me\n\n[Chorus]\nMultiverse highway, endless roads\nMultiverse highway, where all possibilities unfold\nSome paths lead to glory, some lead to pain\nSome to love lost, some to love gained\nMultiverse highway, infinite lanes\nEvery choice we make, creates another way\n\n[Outro]\nI'll keep driving my particular lane\nWondering about the exits I passed\nSomewhere, other versions of me\nAre living the futures I forecast"
        },
        {
            title: "Quantum Entanglement",
            style: "Ethereal duet with perfectly synchronized male and female vocals, mirroring musical phrases, intertwined melodies, distance-defying harmonies, cosmic string arrangements, simultaneous emotional peaks, and interconnected sonic elements",
            lyrics: "[Verse 1]\nSeparated by a thousand miles\nYet I feel your every breath\nWhen your heart skips, mine follows suit\nA connection that defies death\nNo signal passes between us\nNo information needs to flow\nYet somehow we remain connected\nIn ways science cannot show\n\n[Pre-Chorus]\nTwo particles, once united\nRemain linked across all space\nWhat happens to one affects the other\nNo matter the time, no matter the place\n\n[Chorus]\nQuantum entanglement, spooky action at a distance\nQuantum entanglement, defying space and time\nOur souls intertwined beyond physical existence\nWhat happens to you, happens to me\nA cosmic connection, impossible to sever\nLike particles dancing in quantum harmony\n\n[Verse 2]\nI dream your dreams before you tell me\nI feel your pain before you call\nYou know my thoughts before I speak them\nAs if there's no distance at all\nEinstein called it \"spooky action\"\nA paradox he couldn't accept\nBut our hearts know quantum truth\nOur connection transcends concept\n\n[Pre-Chorus]\nTwo particles, once united\nRemain linked across all space\nWhat happens to one affects the other\nNo matter the time, no matter the place\n\n[Chorus]\nQuantum entanglement, spooky action at a distance\nQuantum entanglement, defying space and time\nOur souls intertwined beyond physical existence\nWhat happens to you, happens to me\nA cosmic connection, impossible to sever\nLike particles dancing in quantum harmony\n\n[Bridge]\nIf you were at the edge of the universe\nAnd I remained here on Earth\nThe link between us would not weaken\nInstantaneous connection since birth\nNo force in nature can break this bond\nNo distance can make it decay\nEntangled souls like entangled particles\nConnected in a quantum way\n\n[Chorus]\nQuantum entanglement, spooky action at a distance\nQuantum entanglement, defying space and time\nOur souls intertwined beyond physical existence\nWhat happens to you, happens to me\nA cosmic connection, impossible to sever\nLike particles dancing in quantum harmony\n\n[Outro]\nI'll feel you always\nAcross space and time\nQuantum entangled\nYour heart tied to mine"
        },
        {
            title: "Observer Effect",
            style: "Experimental electronic with reality-shifting production, perception-altering synthesizers, consciousness-themed sound design, observation-dependent arrangements that change with focus, philosophical vocal delivery, and reality-bending sonic textures",
            lyrics: "[Verse 1]\nIs the tree still there when no one looks?\nDoes the moon exist when clouds conceal?\nDoes the world continue spinning\nWhen there's no one there to feel?\nThe quantum world suggests the strangest truth:\nReality depends on observation\nThe act of looking changes what we see\nConsciousness creates manifestation\n\n[Pre-Chorus]\nThe observer and the observed\nLocked in cosmic dance\nNeither fully real without the other\nNeither left to chance\n\n[Chorus]\nThe observer effect, reality shifts under my gaze\nThe observer effect, perception shapes our ways\nNothing exists in definite form\nUntil consciousness makes it so\nThe universe is possibility\nUntil we decide what to know\n\n[Verse 2]\nElectrons act like waves until we look\nThen suddenly behave like points in space\nThe double-slit experiment confirms\nObservation changes what takes place\nPerhaps our lives work just the same way\nPotential shapes until we choose to see\nThe very act of living consciously\nCreates the world that's meant to be\n\n[Pre-Chorus]\nThe observer and the observed\nLocked in cosmic dance\nNeither fully real without the other\nNeither left to chance\n\n[Chorus]\nThe observer effect, reality shifts under my gaze\nThe observer effect, perception shapes our ways\nNothing exists in definite form\nUntil consciousness makes it so\nThe universe is possibility\nUntil we decide what to know\n\n[Bridge]\nWhat if consciousness itself\nIs fundamental to existence?\nWhat if matter is secondary\nTo awareness in persistence?\nWhat if observation isn't passive\nBut creative in its power?\nWhat if we're not just witnesses\nBut creators every hour?\n\n[Chorus]\nThe observer effect, reality shifts under my gaze\nThe observer effect, perception shapes our ways\nNothing exists in definite form\nUntil consciousness makes it so\nThe universe is possibility\nUntil we decide what to know\n\n[Outro]\nI'm looking at the world\nThe world is looking back\nThe observation shapes us both\nIn ways I can't extract"
        },
        {
            title: "Superposition",
            style: "Harmonically complex electronic with peaceful resolution, multiple musical layers that eventually synchronize, quantum meditation atmospherics, enlightened vocal delivery, reconciliation of musical opposites, and transcendent sound design",
            lyrics: "[Verse 1]\nAll possibilities exist at once\nEvery contradiction simultaneously true\nI am particle and wave, certainty and doubt\nPotential unrestricted, flowing through\nThe quantum world accepts what we cannot:\nThat opposites need not be resolved\nThat paradox is natural state\nAnd mystery need not be solved\n\n[Pre-Chorus]\nIn superposition I find peace\nIn both/and, not either/or\nAll states existing together\nInfinite paths through every door\n\n[Chorus]\nSuperposition, all possibilities embraced\nSuperposition, no potential goes to waste\nI am all versions of myself\nAll choices made and unmade too\nSuperposition, freedom in quantum truth\nEvery reality simultaneously alive\n\n[Verse 2]\nThe anxiety of choosing fades away\nWhen I accept all paths as valid and real\nThe FOMO dissipates like morning fog\nWhen parallel lives run alongside what I feel\nI need not wonder what if anymore\nOr regret the roads not taken in my time\nFor somewhere in the quantum multiverse\nEvery mountain I might climb, I climb\n\n[Pre-Chorus]\nIn superposition I find peace\nIn both/and, not either/or\nAll states existing together\nInfinite paths through every door\n\n[Chorus]\nSuperposition, all possibilities embraced\nSuperposition, no potential goes to waste\nI am all versions of myself\nAll choices made and unmade too\nSuperposition, freedom in quantum truth\nEvery reality simultaneously alive\n\n[Bridge]\nThe cat is both alive and dead\nThe electron here and there\nBoth particle and wave at once\nBoth certain and nowhere\nAnd in this quantum paradox\nI find my truest peace\nKnowing everything that could be, is\nSomewhere, immortal, never to cease\n\n[Chorus]\nSuperposition, all possibilities embraced\nSuperposition, no potential goes to waste\nI am all versions of myself\nAll choices made and unmade too\nSuperposition, freedom in quantum truth\nEvery reality simultaneously alive\n\n[Outro]\nThe multiverse contains it all\nEvery path is traveled somewhere\nAnd in this truth I find my rest\nAll possibilities forever there"
        }
    ]
};