// Define album data - making sure it's in the global (window) scope
window.ethereal_ascension_data = {
    folder: "Ethereal Ascension",
    name: "Ethereal Ascension",
    releaseDate: "2025-04-15",
    totalSongs: 9,
    coverArt: "asset/album-name/Ethereal Ascension/Art.jpg",
    songsData: [
        {
            title: "Azure Phoenix Rising",
            style: "Symphonic electronic metal fusion, Atmospheric orchestral elements, Soaring vocals, Heavy percussion with electronic beats, Electric guitar riffs with ethereal synthesizers, Dramatic choruses",
            lyrics: "[Verse 1]\nIn shadows cast by broken wings\nAzure flames ignite the night\nRising from the ashes deep\nBreaking chains that held me tight\n\n[Chorus]\nLike a phoenix born in blue\nDancing in the flames anew\nLet these wings of darkness soar\nThrough the gates of nevermore\nWhile the embers light my way\nTo the dawn of healing day\n\n[Verse 2]\nShattered feathers paint the sky\nAs my spirit learns to fly\nIn this moment I am free\nBurning bright for all to see\n\n[Bridge]\nThrough the veil of endless night\nWatch my essence take its flight\nIn these flames I am reborn\nAs the darkness turns to morn\n\n[Chorus]\nLike a phoenix born in blue\nDancing in the flames anew\nLet these wings of darkness soar\nThrough the gates of nevermore\nWhile the embers light my way\nTo the dawn of healing day\n\n[Outro]\nIn azure light I rise again\nForever free from mortal pain\nA guardian of twilight's reign\nIn eternal blue flame"
        },
        {
            title: "Wings of Digital Flame",
            style: "Electronic dance-pop with melodic dubstep drops, Progressive house elements, Future bass synths, Cinematic orchestral sections, Ethereal vocal chops, Heavy sidechaining, Energetic builds and emotional",
            lyrics: "[Verse 1]\nIn a world of binary dreams\nWhere nothing's quite what it seems\nDigital wings spread wide and bright\nBreaking through the darkest night\nFlickering like neon rain\nCode rewrites my soul again\n\n[Pre-Chorus]\nFeel the fire in my veins\nAs the system breaks its chains\nWatch me rise above the ground\nWhen the beat comes crashing down\n\n[Chorus]\nThese wings of digital flame\nWill never be the same\nRising through electric skies\nWatch me as I come alive\nIn the night we'll burn so bright\nDancing in computer light\nNothing's gonna be the same\nWith these wings of digital flame\n\n[Verse 2]\nPixels scatter through the air\nAs blue fire everywhere\nTransforms what used to be\nInto what they'll never see\nProgramming my destiny\nIn this virtual reality\n\n[Bridge]\nHigher, higher we will soar\nBreaking through the virtual door\nFeel the power surge and flow\nAs these wings begin to glow\n(Electronic instrumental drop)\n\n[Chorus]\nThese wings of digital flame\nWill never be the same\nRising through electric skies"
        },
        {
            title: "Midnight Protocol",
            style: "Electronic dance with future bass elements, Dark electro-pop beats, Hard-hitting drops with melodic synth leads, Atmospheric pads, Punchy drums with heavy sidechaining, Glitch effects, Filtered vocal",
            lyrics: "[Verse 1]\nSystem override, breaking through\nElectric storms of midnight blue\nThey said I couldn't touch the sky\nNow watch these wings of mine defy\nEvery rule they wrote in stone\nEvery limit I've been shown\n\n[Pre-Chorus]\nFeel it coming like a wave\nDigital soul I cannot save\nThree, two, one, about to break\nThis is all I'm gonna take\n\n[Chorus]\nTonight we're running protocols\nBreaking every firewall\nWatch me burn in shades of blue\nCoding something wild and new\nCan't contain this energy\nDigital infinity\nBreaking free from gravity\nThis is my reality\n\n[Verse 2]\nCircuit breakers blown away\nAs these wings light up the way\nThrough the matrix of the night\nAlgorithm set alight\nReprogramming what they see\nInto what I'm meant to be\n\n[Bridge]\n(Building electronic tension)\nLoading... Loading...\nSystem failure imminent\nWarning... Warning...\nNew protocol emergent\n(Massive drop with soaring synths)\n\n[Chorus]\nTonight we're running protocols\nBreaking every firewall\nWatch me burn in shades of blue\nCoding something wild and new\nCan't contain this energy\nDigital infinity\nBreaking free from gravity\nThis is my reality\n\n[Outro]\nIn the silence of the code\nWhere digital wings explode\nBreaking free from what we know\nLet the midnight protocol flow"
        },
        {
            title: "Electric Skies Rising",
            style: "High-energy electronic dance, Future bass with progressive house elements, Euphoric synth leads, Punchy drum patterns, Cinematic breakdowns, Powerful bass drops, Emotional piano undertones",
            lyrics: "[Verse 1]\nSilent city down below\nWhile electric currents flow\nThrough the darkness of the night\nFeel the power take its flight\nEvery heartbeat synchronized\nTo the rhythm of the skies\n\n[Pre-Chorus]\nFeel the static in the air\nAs these wings begin to flare\nBuilding up inside of me\nEnergy about to break free\n\n[Chorus]\nWe're rising through electric skies\nWhere lightning never dies\nThese wings of storm and steel\nMake everything feel real\nNo gravity can hold us now\nThe night is ours somehow\nAs thunder rolls away\nWatch this lightning display\n\n[Verse 2]\nStorm clouds gather overhead\nAs the neon turns to red\nBut these wings of blue ignite\nTurn the darkness into light\nBreaking through the atmosphere\nMaking history right here\n\n[Bridge]\n[Quiet electronic build-up]\nFeel it building in the night\nLike a storm about to break\nPower surging left and right\nThis is more than we can take\n[Massive melodic drop]\n\n[Chorus]\nWe're rising through electric skies\nWhere lightning never dies\nThese wings of storm and steel\nMake everything feel real\nNo gravity can hold us now\nThe night is ours somehow\nAs thunder rolls away\nWatch this lightning display\n\n[Outro]\nIn this moment we are free\nSoaring through infinity\nElectric wings light up the dark\nLeave behind a glowing mark"
        },
        {
            title: "Ethereal Override",
            style: "High-impact electronic dance, Melodic bass music with orchestral elements, Energetic drops with emotional buildups, Crystal synth leads, Heavy sidechained bass, Glitch percussion, Cinematic breaks",
            lyrics: "[Verse 1]\nFragments of a fading light\nAs the code rewrites the night\nFeel the power surge within\nLet this journey now begin\nEvery pulse of binary\nSets these wings of darkness free\n\n[Pre-Chorus]\nOn the edge of breaking through\nWhere the virtual turns to blue\nFeel the system overload\nAs these wings of light explode\n\n[Chorus]\nWe're breaking through dimensions now\nThese wings will show us how\nTo override the rules of flight\nAnd set this world alight\nThe code is running wild and free\nThrough digital infinity\nNo stopping what's about to be\nThis ethereal prophecy\n\n[Verse 2]\nNeon traces in the sky\nAs these wings begin to fly\nThrough the matrix of the night\nEvery pixel burning bright\nReprogramming gravity\nInto what we're meant to be\n\n[Bridge]\n[Soft electronic meditation]\nSystem status: Critical\nFirewall: Disabled\nOverride: Initiated\nEvolution: Activated\n[Massive melodic drop with soaring synths]\n\n[Chorus]\nWe're breaking through dimensions now\nThese wings will show us how\nTo override the rules of flight\nAnd set this world alight\nThe code is running wild and free\nThrough digital infinity\nNo stopping what's about to be\nThis ethereal prophecy\n\n[Outro]\nIn the space between the code\nWhere digital dreams explode\nWatch these wings of light transcend\nWhere reality will bend"
        },
        {
            title: "Quantum Ascension",
            style: "High-energy electronic fusion, Progressive melodic bass, Cinematic dubstep elements, Euphoric synthesizer leads, Hard-hitting percussion with glitch effects, Atmospheric soundscapes, Powerful bass",
            lyrics: "[Verse 1]\nIn the void between the stars\nWhere quantum light leaves ancient scars\nFeel the power coursing deep\nAs these wings begin to leap\nThrough dimensions unexplored\nEvery boundary ignored\n\n[Pre-Chorus]\nCan you feel it in your soul?\nAs these frequencies unfold\nWatch the energy ignite\nAs we break the speed of light\n\n[Chorus]\nQuantum wings of blue fire rise\nThrough the boundaries of the skies\nBreaking physics as we soar\nTo heights we've never reached before\nFeel the power amplify\nAs we learn to touch the sky\nNothing's ever gonna be the same\nSince these wings became our flame\n\n[Verse 2]\nParticles collide and dance\nIn this quantum resonance\nAs these wings of light divide\nEvery rule we left behind\nAccelerating through the night\nPast the limits of our sight\n\n[Bridge]\n[Quiet electronic buildup]\nCalculating trajectory\nBreaking probability\nQuantum state: Activated\nReality: Elevated\n[Massive synth drop with soaring melody]\n\n[Chorus]\nQuantum wings of blue fire rise\nThrough the boundaries of the skies\nBreaking physics as we soar\nTo heights we've never reached before\nFeel the power amplify\nAs we learn to touch the sky\nNothing's ever gonna be the same\nSince these wings became our flame\n\n[Outro]\nIn this quantum dance of light\nWhere dimensions take their flight\nWatch these wings of change unfold\nAs new stories will be told"
        },
        {
            title: "Starborn Legacy",
            style: "Epic electronic dance fusion, Interstellar soundscapes, Cosmic bass drops, Ethereal vocal textures, Pulsing rhythms with celestial synths, Dramatic orchestral elements, Space-age sound design",
            lyrics: "[Verse 1]\nBorn from stardust long ago\nAncient power starts to flow\nCosmic wings begin to rise\nThrough the boundaries of skies\nEvery constellation burns\nAs this legacy returns\n\n[Pre-Chorus]\nFeel the stellar energy\nCoursing through our destiny\nWatch these wings ignite the night\nWith a supernatural light\n\n[Chorus]\nWe are children of the stars\nBreaking through these mortal bars\nLet these cosmic wings unfold\nStories that were never told\nFeel the universe align\nAs we cross the grand design\nNothing's gonna be the same\nSince we found our stellar flame\n\n[Verse 2]\nNebulas of burning blue\nPaint the path we're rushing through\nPast the edge of time and space\nLeaving not a single trace\nEvery galaxy we meet\nMakes this journey more complete\n\n[Bridge]\n[Celestial build-up]\nStarlight flowing through our veins\nBreaking all these mortal chains\nWatch the cosmos come alive\nAs our spirits learn to thrive\n[Massive cosmic drop]\n\n[Chorus]\nWe are children of the stars\nBreaking through these mortal bars\nLet these cosmic wings unfold\nStories that were never told\nFeel the universe align\nAs we cross the grand design\nNothing's gonna be the same\nSince we found our stellar flame\n\n[Outro]\nIn this cosmic dance of light\nWhere the stars ignite our flight\nWatch these wings of space and time\nMake this moment so sublime"
        },
        {
            title: "Infinite Awakening",
            style: "High-intensity electronic production, Future bass with melodic dubstep fusion, Ethereal sound design, Powerful synthesizer leads, Hard-hitting percussion with glitch elements, Sweeping atmospheric pad",
            lyrics: "[Verse 1]\nFrozen in a timeless dream\nWhere nothing's ever what it seems\nFeel these wings begin to glow\nAs dimensions overflow\nEvery limit fades away\nIn this endless light display\n\n[Pre-Chorus]\nStanding at the edge of time\nWhere infinity aligns\nWatch this power come alive\nAs these wings begin to thrive\n\n[Chorus]\nWe're awakening tonight\nBreaking through the speed of light\nLet these wings of change unfold\nAs new stories will be told\nFeel eternity align\nPast the boundaries of time\nNothing's ever gonna be\nWhat infinity set free\n\n[Verse 2]\nDancing through the astral plane\nWhere dimensions break their chain\nAs these wings of light ignite\nEvery shadow takes its flight\nBreaking barriers unknown\nTo a place we'll call our home\n\n[Bridge]\n[Ethereal build-up]\nFeel the power in your soul\nAs dimensions start to roll\nWatch reality unfold\nAs new legends will be told\n[Massive melodic drop]\n\n[Chorus]\nWe're awakening tonight\nBreaking through the speed of light\nLet these wings of change unfold\nAs new stories will be told\nFeel eternity align\nPast the boundaries of time\nNothing's ever gonna be\nWhat infinity set free\n\n[Outro]\nIn this space between the dreams\nWhere infinity redeems\nWatch these wings of time ignite\nMake the darkness turn to light"
        },
        {
            title: "Fallen Horizon",
            style: "Dark electronic anthem, Emotional future bass elements, Heavy melodic bass music, Cinematic builds with orchestral undertones, Haunting vocal layers, Intense percussion design, Epic synthesizer leads",
            lyrics: "[Verse 1]\nStanding at the edge of dawn\nWhere broken dreams are drawn\nThese wings of darkness rise\nThrough apocalyptic skies\nEvery fear we've known\nTurns to power on its own\n\n[Pre-Chorus]\nOn the brink of letting go\nAs these flames begin to grow\nWatch the darkness turn to light\nAs we prepare to take our flight\n\n[Chorus]\nTonight we're falling through the sky\nWhere horizons never die\nLet these wings of flame ignite\nTurn our shadows into light\nFeel the power break away\nAs we learn to disobey\nNothing's gonna be the same\nSince we found our azure flame\n\n[Verse 2]\nBreaking through reality\nWhere lost souls long to be free\nAs these wings of change emerge\nPast the boundaries we surge\nEvery limit faced before\nFalls apart as now we soar\n\n[Bridge]\n[Intense electronic build]\nFeel it rising from below\nAs these embers start to glow\nWatch your fears all fade away\nAs blue fire leads the way\n[Massive melodic drop]\n\n[Chorus]\nTonight we're falling through the sky\nWhere horizons never die\nLet these wings of flame ignite\nTurn our shadows into light\nFeel the power break away\nAs we learn to disobey\nNothing's gonna be the same\nSince we found our azure flame\n\n[Outro]\nIn this space between the night\nWhere lost dreams take their flight\nWatch these wings of change unfold\nAs new stories will be told"
        }
    ]
};