// Crimson Warrior - 7 Songs Inspired by Dark Armored Knight Image
window.crimson_warrior_data = {
    folder: "Crimson Warrior",
    name: "Crimson Warrior",
    releaseDate: "2025-06-26",
    totalSongs: 7,
    coverArt: "asset/album-name/Crimson Warrior/Art.png",
    songsData: [
        {
            title: "Crimson Steel Awakening",
            style: "Symphonic electronic metal fusion, Dark orchestral elements, Heavy percussion with electronic beats, Menacing synthesizers, Dramatic choruses, Industrial soundscapes",
            lyrics: "[Verse 1]\nThey called me brother, called me friend\nUntil the lies began to spread\nPoison words and silver tongues\nTurned my allies against their blood\nNow I stand with crimson steel\nFacing those who made me kneel\n\n[Chorus]\nBetrayed by those I called my own\nNow I fight these wars alone\nCrimson blade against the night\nFor my honor, for what's right\nThough they paint me as the foe\nTruth is all I'll ever know\n\n[Verse 2]\nArmor stained with blood and tears\nFighting through my darkest fears\nThousand swords against just one\nBut I'll fight till day is done\nEvery scar upon my flesh\nProves my loyalty was fresh\n\n[Bridge]\nHear the thunder of their march\nAs they come with fire and torch\nBut my conscience burns more bright\nThan their armies in the night\n\n[Chorus]\nBetrayed by those I called my own\nNow I fight these wars alone\nCrimson blade against the night\nFor my honor, for what's right\nThough they paint me as the foe\nTruth is all I'll ever know\n\n[Outro]\nWhen the crimson dawn arrives\nThey'll remember who survives\nNot for glory, not for fame\nBut to clear my tainted name"
        },
        {
            title: "Blood Moon Ritual",
            style: "Electronic dance with dark electro-pop beats, Heavy melodic bass drops, Atmospheric industrial pads, Glitch effects with orchestral stabs, Punchy drums with crimson energy, Cinematic builds",
            lyrics: "[Verse 1]\nMessages of lies and deceit\nSpread through every castle street\nFalse evidence forged with care\nTo frame the knight who always dared\nRoyal orders written in haste\nTo see my legacy erased\n\n[Pre-Chorus]\nSee the crimson moon arise\nWitness to their wicked lies\nThree, two, one, the trap is set\nBut they haven't won yet\n\n[Chorus]\nBlood moon ritual in play\nTurning brothers all away\nEvery ally now believes\nIn the web that deception weaves\nStanding lonely in the night\nI prepare for final fight\nThough the odds are stacked so high\nI would rather fight than lie\n\n[Verse 2]\nTorch flames burning with betrayal\nAs the truth begins to pale\nEvery friend now sees a foe\nIn the knight they used to know\nBut my heart remains so pure\nOf this I can be sure\n\n[Bridge]\n(Building orchestral tension)\nHear them... Armies gathering...\nRoyal decree: Eliminate traitor\nWarning... Standing alone...\nMission: Survive till dawn\n(Massive drop with battle synths)\n\n[Chorus]\nBlood moon ritual in play\nTurning brothers all away\nEvery ally now believes\nIn the web that deception weaves\nStanding lonely in the night\nI prepare for final fight\nThough the odds are stacked so high\nI would rather fight than lie\n\n[Outro]\nWhen the blood moon fades away\nTruth will see the light of day\nBut tonight I stand alone\nFighting for what I have known"
        },
        {
            title: "Armored Soul",
            style: "High-energy electronic fusion with symphonic metal elements, Dark melodic bass, Epic orchestral sections, Heavy percussion design, Emotional piano undertones, Powerful synth leads",
            lyrics: "[Verse 1]\nBeneath this steel that guards my heart\nLies a soul that's torn apart\nEvery plate of armor worn\nCarries weight of love now scorned\nThose I trusted, those I saved\nNow want me buried in my grave\n\n[Pre-Chorus]\nCan they see beyond their hate?\nTo the truth before too late\nEvery wound that I endure\nIs for them, of this I'm sure\n\n[Chorus]\nArmored soul, heart so true\nFighting for the ones who never knew\nEvery step I take tonight\nIs to set their future right\nThough they curse my very name\nI will bear their scorn and shame\nFor the innocent must live\nEven if I cannot forgive\n\n[Verse 2]\nOnce we stood as brothers strong\nNow they sing betrayal's song\nBut beneath this crimson steel\nBeats a heart that's always real\nI remember who they were\nBefore lies began to stir\n\n[Bridge]\n[Emotional electronic build-up]\nRemember all the times we shared\nBefore they stopped and declared\nThat the knight who saved their lives\nIs the one who now deprives\n[Powerful melodic drop]\n\n[Chorus]\nArmored soul, heart so true\nFighting for the ones who never knew\nEvery step I take tonight\nIs to set their future right\nThough they curse my very name\nI will bear their scorn and shame\nFor the innocent must live\nEven if I cannot forgive\n\n[Outro]\nWhen this armor falls to ground\nMaybe then the truth is found\nThat the heart beneath the steel\nAlways kept their love so real"
        },
        {
            title: "Throne of Shadows",
            style: "Dark electronic anthem with industrial elements, Heavy dubstep drops, Orchestral dramatic builds, Menacing vocal processing, Intense percussion with glitch effects, Epic synthesizer leads",
            lyrics: "[Verse 1]\nThey offered me a throne of lies\nBuilt on innocent people's cries\nTo join them in their wicked scheme\nAnd shatter every righteous dream\nBut I chose to stand apart\nWith honor burning in my heart\n\n[Pre-Chorus]\nNow they hunt me through the night\nTurning wrong into their right\nEvery shadow hides a blade\nFrom the choices that I've made\n\n[Chorus]\nNo throne of shadows for my soul\nI won't play their twisted role\nStanding firm against the tide\nWith my conscience as my guide\nThough a thousand armies come\nI will not be overcome\nFor the truth is worth the fight\nEven in this endless night\n\n[Verse 2]\nCrowns of gold mean nothing here\nWhen built upon the people's fear\nI would rather die alone\nThan sit upon that cursed throne\nMy legacy won't be their shame\nI'll die protecting my true name\n\n[Bridge]\n[Intense orchestral build]\nHear the armies as they march\nUnderneath corruption's arch\nBut I'll stand here till the end\nWith no allies to defend\n[Massive drop with choir elements]\n\n[Chorus]\nNo throne of shadows for my soul\nI won't play their twisted role\nStanding firm against the tide\nWith my conscience as my guide\nThough a thousand armies come\nI will not be overcome\nFor the truth is worth the fight\nEven in this endless night\n\n[Outro]\nWhen the final horn is blown\nI'll have earned my rightful throne\nNot of shadows, but of light\nBuilt on doing what is right"
        },
        {
            title: "Hellfire Ascendant",
            style: "High-impact electronic dance with orchestral fusion, Melodic bass music with dark elements, Energetic drops with apocalyptic buildups, Heavy sidechained bass, Cinematic fire sound design",
            lyrics: "[Verse 1]\nThousand soldiers charge my way\nBut I'll make them rue this day\nEvery arrow, every spear\nCannot pierce through my veneer\nHellfire burns within my soul\nAs I fight to reach my goal\n\n[Pre-Chorus]\nFeel the heat begin to rise\nAs I look into their eyes\nSee the doubt begin to grow\nAs my crimson powers show\n\n[Chorus]\nHellfire ascendant, burning bright\nOne against a thousand in this fight\nEvery strike they throw my way\nOnly makes my fire blaze\nI am outnumbered but not outmatched\nFrom this nightmare I'll be snatched\nBy the truth that burns so pure\nThat my victory is sure\n\n[Verse 2]\nBattlefields of endless red\nPiled high with the misled\nThrough the chaos I advance\nGiving honor one last chance\nEvery fallen warrior's face\nKnows they're fighting in disgrace\n\n[Bridge]\n[Building battle sound effects]\nHear the clash of steel on steel\nAs I make my final deal\nDeath before dishonor's stain\nLet my sacrifice remain\n[Massive synth drop with war drums]\n\n[Chorus]\nHellfire ascendant, burning bright\nOne against a thousand in this fight\nEvery strike they throw my way\nOnly makes my fire blaze\nI am outnumbered but not outmatched\nFrom this nightmare I'll be snatched\nBy the truth that burns so pure\nThat my victory is sure\n\n[Outro]\nWhen the hellfire fades away\nThey'll remember this last day\nOne knight stood against them all\nAnswering honor's final call"
        },
        {
            title: "Warrior's Lament",
            style: "Emotional electronic ballad with symphonic elements, Dark ambient soundscapes, Melancholic piano melodies, Ethereal vocal textures, Subtle electronic beats, Orchestral string arrangements",
            lyrics: "[Verse 1]\nIn the quiet before the storm\nMy heart is heavy and worn\nI think of all the lives I've saved\nNow wanting me in my grave\nDid all my service mean so little?\nThat lies could make their hearts so brittle?\n\n[Pre-Chorus]\nDo the heavens hear my prayer?\nIn this moment of despair\nWill they know when I am gone\nThat my honor carried on?\n\n[Chorus]\nThis is the warrior's lament\nFor the loyalty I've spent\nEvery battle fought with pride\nNow they're standing on their side\nI will die here all alone\nFor the truth I've always known\nBut I'll carry it with grace\nTo my final resting place\n\n[Verse 2]\nMemories of better days\nWhen they sang my warrior's praise\nNow those same voices call for blood\nDrowning truth beneath the mud\nBut I know that time will tell\nWho served his people well\n\n[Bridge]\n[Soft orchestral meditation]\nIn these final moments here\nI shed one last lonely tear\nNot for death that's drawing near\nBut for friends I held so dear\n[Emotional string crescendo]\n\n[Chorus]\nThis is the warrior's lament\nFor the loyalty I've spent\nEvery battle fought with pride\nNow they're standing on their side\nI will die here all alone\nFor the truth I've always known\nBut I'll carry it with grace\nTo my final resting place\n\n[Outro]\nWhen my story finally ends\nMay they remember we were friends\nBefore the lies tore us apart\nI loved them with my warrior's heart"
        },
        {
            title: "Apocalypse Unleashed",
            style: "Extreme electronic metal fusion, Industrial dubstep elements, Apocalyptic orchestral arrangements, Heavy distorted bass, Aggressive percussion design, Chaotic glitch effects, Epic choir sections",
            lyrics: "[Verse 1]\nThe final hour has arrived\nThough outnumbered I have strived\nTo hold the line till my last breath\nFacing honor before death\nEvery weapon raised in war\nAs I fall on crimson floor\n\n[Pre-Chorus]\nCan you hear the battle roar?\nAs they end this righteous war\nFeel the ground beneath me break\nAs my final stand I make\n\n[Chorus]\nApocalypse unleashed claims my life\nEnding all this bitter strife\nWith my dying breath I cry\nFor the truth that cannot die\nWhen my crimson blood runs cold\nLet my story then be told\nHow one knight stood against the tide\nWith only honor by his side\n\n[Verse 2]\nAs my vision starts to fade\nI see the price that I have paid\nBut in my heart I know it's right\nTo die here in this hopeless fight\nFor when they find what I have saved\nThey'll know I was not depraved\n\n[Bridge]\n[Building war drums and chaos]\nHear the truth begin to rise\nFrom beneath their web of lies\nEvery secret I've protected\nWill leave their schemes detected\n[Massive orchestral drop with revelation choir]\n\n[Chorus]\nApocalypse unleashed claims my life\nEnding all this bitter strife\nWith my dying breath I cry\nFor the truth that cannot die\nWhen my crimson blood runs cold\nLet my story then be told\nHow one knight stood against the tide\nWith only honor by his side\n\n[Outro]\nNow they see what I have done\nHow their battles have been won\nBy the knight they thought their foe\nNow they finally know\nIn the silence of my grave\nLies the kingdom that I saved"
        }
    ]
};