// Define album data - making sure it's in the global (window) scope
window.voices_in_the_dark_data = {
    folder: "Voices in the Dark",
    name: "Voices in the Dark",
    releaseDate: "2025-03-24",
    totalSongs: 7,
    coverArt: "asset/album-name/Voices in the Dark/Art.jpg",
    songsData: [
        {
            title: "Whispers Begin",
            style: "Ambient Electronic, minimal piano, atmospheric pads, subtle vocal samples, building tension, quiet percussion, haunting melodies, introductory instrumental with brief vocals",
            lyrics: "[Verse 1]\nSilent room, fading light\nSomething's different here tonight\nShadows move against the wall\nVoices whisper, so small\nAm I dreaming? Am I awake?\nReality starting to break\n\n[Pre-Chorus]\nThey're getting closer\nInside my mind\nThey're getting louder\nLeaving reality behind\n\n[Chorus]\nWhispers begin in the darkness\nEchoes of thoughts in my head\nWhispers begin, I can't stop them\nFollowing where I am led\nFading away from what's real now\nInto a world of my own\nWhispers begin in the shadows\nI'm not alone, not alone\n\n[Verse 2]\nNormal life slips away\nVoices growing day by day\nTrying hard to shut them out\nBut they know what I'm about\nAm I fading? Am I lost?\nReality lines being crossed\n\n[Pre-Chorus]\nThey're getting closer\nInside my mind\nThey're getting louder\nLeaving reality behind\n\n[Chorus]\nWhispers begin in the darkness\nEchoes of thoughts in my head\nWhispers begin, I can't stop them\nFollowing where I am led\nFading away from what's real now\nInto a world of my own\nWhispers begin in the shadows\nI'm not alone, not alone\n\n[Outro]\nWhispers begin\nWhispers begin\nWhispers begin\nI'm not alone"
        },
        {
            title: "Watching Eyes",
            style: "Electronic Pop, future bass elements, moody synthesizers, ghostly vocals, subtle bass drops, rhythmic percussion, melancholic melodies, building electronic tension",
            lyrics: "[Verse 1]\nFeel them watching as I sleep\nEyes that never seem to blink\nIn the corners of my mind\nIn the shadows hard to find\nNowhere safe for me to hide\nFrom these eyes that look inside\n\n[Pre-Chorus]\nCan you feel them?\nStaring through me\nCan you see them?\nAs they surround me\n\n[Chorus]\nWatching eyes that never fade\nSeeing through the walls I've made\nWatching eyes that follow me\nInto dreams, won't let me be\nFading deeper into night\nLosing touch with what is right\nWatching eyes won't look away\nLost in shadows, here I stay\n\n[Verse 2]\nTry to run but they still see\nMultiplying endlessly\nGlowing pink in darkened space\nWatching every move I make\nJudging thoughts inside my head\nWhispering the things unsaid\n\n[Pre-Chorus]\nCan you feel them?\nStaring through me\nCan you see them?\nAs they surround me\n\n[Chorus]\nWatching eyes that never fade\nSeeing through the walls I've made\nWatching eyes that follow me\nInto dreams, won't let me be\nFading deeper into night\nLosing touch with what is right\nWatching eyes won't look away\nLost in shadows, here I stay\n\n[Outro]\nWatching eyes\nWatching eyes\nFading, fading\nStill they're watching me"
        },
        {
            title: "Reaching Shadows",
            style: "Dark Electronic, industrial elements, distorted bass, eerie vocal effects, glitchy percussion, ominous synthesizers, building intensity, chaotic breakdowns",
            lyrics: "[Verse 1]\nShadow hands reach through the walls\nGrasping, pulling, want it all\nReaching for what's deep inside\nNo more places left to hide\nAm I fading? Am I gone?\nShadows pulling me along\n\n[Pre-Chorus]\nI'm disappearing\nAs they pull me deeper\nI'm disappearing\nAs darkness gets steeper\n\n[Chorus]\nReaching shadows pull me down\nInto darkness all around\nReaching shadows, cold as ice\nTaking over, paying price\nFading deeper out of sight\nLosing touch with morning light\nReaching shadows won't let go\nTaking me where I don't know\n\n[Verse 2]\nTry to run but they still reach\nEvery corner, every breach\nFinger-like and void of warmth\nChanging me, changing form\nAm I breaking? Am I lost?\nShadows spreading at what cost?\n\n[Pre-Chorus]\nI'm disappearing\nAs they pull me deeper\nI'm disappearing\nAs darkness gets steeper\n\n[Chorus]\nReaching shadows pull me down\nInto darkness all around\nReaching shadows, cold as ice\nTaking over, paying price\nFading deeper out of sight\nLosing touch with morning light\nReaching shadows won't let go\nTaking me where I don't know\n\n[Outro]\nReaching shadows\nReaching shadows\nFading, fading\nInto shadows"
        },
        {
            title: "Consumed",
            style: "Heavy EDM, aggressive drops, chaotic sound design, distorted vocals, powerful bass, frantic percussion, intense build-ups, overwhelming electronic elements",
            lyrics: "[Verse 1]\nLost within this thing inside\nDarkness grown too large to hide\nMany eyes now watching me\nFrom within, can't break free\nAm I vanished? Am I gone?\nConsumption has been too long\n\n[Pre-Chorus]\nSlipping away now\nInto the void\nSlipping away now\nCompletely destroyed\n\n[Chorus]\nConsumed by the voices inside\nLost in a world of my own design\nConsumed as I fade away\nNothing of me left to stay\nFading further from the light\nLosing battles, losing fight\nConsumed by the eyes that see\nNothing left that's still just me\n\n[Verse 2]\nSurrendered to the dark within\nForgotten where I once begin\nReplaced by something not my own\nTaken over, overthrown\nAm I ended? Am I through?\nNothing left that I can do\n\n[Pre-Chorus]\nSlipping away now\nInto the void\nSlipping away now\nCompletely destroyed\n\n[Chorus]\nConsumed by the voices inside\nLost in a world of my own design\nConsumed as I fade away\nNothing of me left to stay\nFading further from the light\nLosing battles, losing fight\nConsumed by the eyes that see\nNothing left that's still just me\n\n[Outro]\nConsumed completely\nConsumed completely\nFading, fading\nNothing left of me"
        },
        {
            title: "Fighting Back",
            style: "Melodic Dubstep, determined vocals, powerful bass drops, inspirational chord progressions, energetic rhythms, dynamic electronic build-ups, emotional intensity",
            lyrics: "[Verse 1]\nSpark of light in endless dark\nTiny flame, a single spark\nRemembering who I used to be\nBefore the shadows took from me\nAm I rising? Am I strong?\nFighting what's been there too long\n\n[Pre-Chorus]\nFinding courage\nTo face the night\nFinding courage\nTo bring back light\n\n[Chorus]\nFighting back against the dark\nFinding strength within my heart\nFighting back with fading breath\nBreaking free from living death\nRising up toward the light\nRefusing now to lose this fight\nFighting back against the eyes\nNo longer lost in their lies\n\n[Verse 2]\nThough the shadows still remain\nI'm finding paths through all the pain\nGathering pieces of my soul\nTrying to make myself whole\nAm I winning? Can I be?\nStrong enough to break free?\n\n[Pre-Chorus]\nFinding courage\nTo face the night\nFinding courage\nTo bring back light\n\n[Chorus]\nFighting back against the dark\nFinding strength within my heart\nFighting back with fading breath\nBreaking free from living death\nRising up toward the light\nRefusing now to lose this fight\nFighting back against the eyes\nNo longer lost in their lies\n\n[Outro]\nFighting back\nFighting back\nNo longer fading\nI'm fighting back"
        },
        {
            title: "Different Kind of Light",
            style: "Progressive Electronic, hopeful vocals, atmospheric builds, inspiring synthesizers, gentle piano elements, uplifting drops, emotional chord progressions, healing energy",
            lyrics: "[Verse 1]\nLearning now a different truth\nShadows aren't my enemy\nEyes that watch are part of me\nHands that reach, my history\nAm I changing? Am I seeing?\nNew perspective, new meaning\n\n[Pre-Chorus]\nUnderstanding\nThrough different eyes\nUnderstanding\nNo need to despise\n\n[Chorus]\nA different kind of light inside\nNot blinding white but shades of grey\nA different kind of light to find\nAccepting all that makes me, me\nNo longer fading from myself\nEmbracing what I tried to flee\nA different kind of light now shines\nIlluminating differently\n\n[Verse 2]\nDark and light in harmony\nVoices now speak differently\nEyes that watch with new intent\nReaching hands now represent\nAm I healing? Am I whole?\nFragments forming into soul\n\n[Pre-Chorus]\nUnderstanding\nThrough different eyes\nUnderstanding\nNo need to despise\n\n[Chorus]\nA different kind of light inside\nNot blinding white but shades of grey\nA different kind of light to find\nAccepting all that makes me, me\nNo longer fading from myself\nEmbracing what I tried to flee\nA different kind of light now shines\nIlluminating differently\n\n[Outro]\nDifferent kind of light\nDifferent kind of light\nNo longer fading\nJust a different light"
        },
        {
            title: "Living With The Voices",
            style: "Cinematic Electronic, emotional vocals, orchestral elements, powerful drops, triumphant progressions, reflective melodies, conclusive atmosphere",
            lyrics: "[Verse 1]\nStill I hear the voices speak\nStill the eyes continue watching\nShadow hands sometimes reach\nBut everything has changed now\nAm I stronger? Have I grown?\nLearned to live with not alone\n\n[Pre-Chorus]\nFinally seeing\nWhat I couldn't before\nFinally feeling\nComplete to my core\n\n[Chorus]\nLiving with the voices inside\nNo longer fighting what is mine\nLiving with the eyes that see\nAll the parts that make up me\nNo more fading, standing tall\nAccepting shadows, accepting all\nLiving with what once seemed strange\nIn this balance, I remain\n\n[Verse 2]\nThrough the darkness came the light\nThrough acceptance came the healing\nFind the beauty in the night\nFind the purpose in the feeling\nAm I complete? Am I found?\nWhispers now a gentler sound\n\n[Pre-Chorus]\nFinally seeing\nWhat I couldn't before\nFinally feeling\nComplete to my core\n\n[Chorus]\nLiving with the voices inside\nNo longer fighting what is mine\nLiving with the eyes that see\nAll the parts that make up me\nNo more fading, standing tall\nAccepting shadows, accepting all\nLiving with what once seemed strange\nIn this balance, I remain\n\n[Outro]\nLiving with the voices\nLiving with the shadows\nNo longer fading\nI am whole"
        }
    ]
};