// Define album data - making sure it's in the global (window) scope
window.pandemic_diaries_data = {
    folder: "Pandemic Diaries",
    name: "Pandemic Diaries",
    releaseDate: "2025-04-17",
    totalSongs: 7,
    coverArt: "asset/album-name/Pandemic Diaries/Art.jpg",
    songsData: [
        {
            title: "Day Zero",
            style: "Atmospheric alternative with news broadcast samples, tension-building percussion, anxiety-laden piano motifs, modern electronic elements, warning siren effects, and gradually mounting urgency",
            lyrics: "[Verse 1]\nHeadlines flash across the screen\nA distant threat now drawing near\nRumors spreading faster than the virus\nUncertainty begins to bloom\nIn hospital halls and living rooms\nWhile leaders debate how serious\n\n[Pre-Chorus]\nThe world holds its breath\nOn the edge of something unknown\nThe calm before the storm\nBefore everything changed\n\n[Chorus]\nDay Zero, the moment before the fall\nDay Zero, when life seemed invincible\nThe invisible line between before and after\nThe last exhale of normalcy\nBefore the world stopped turning\nDay Zero, the final hours of innocence\n\n[Verse 2]\nShopping carts filled to the brim\nLast hugs given with nervous grins\n\"See you soon\" we said, not knowing when\nAirports closing one by one\nSirens wailing under the sun\nThe first lockdowns have just begun\n\n[Pre-Chorus]\nThe world holds its breath\nOn the edge of something unknown\nThe calm before the storm\nBefore everything changed\n\n[Chorus]\nDay Zero, the moment before the fall\nDay Zero, when life seemed invincible\nThe invisible line between before and after\nThe last exhale of normalcy\nBefore the world stopped turning\nDay Zero, the final hours of innocence\n\n[Bridge]\nIn history books they'll mark this time\nWhen everything shifted in the blink of an eye\nThe last movie in a crowded theater\nThe last concert with bodies pressed tight\nThe last carefree breath without fear\nBefore masks became armor for life\n\n[Chorus]\nDay Zero, the moment before the fall\nDay Zero, when life seemed invincible\nThe invisible line between before and after\nThe last exhale of normalcy\nBefore the world stopped turning\nDay Zero, the final hours of innocence\n\n[Outro]\nThe clock strikes midnight\nA new calendar begins\nNothing will be the same again"
        },
        {
            title: "Empty Streets",
            style: "Hauntingly beautiful indie folk, sparse acoustic guitar, echoing percussion mimicking footsteps in vacant spaces, ambient urban silence recordings, and emotionally vulnerable vocals",
            lyrics: "[Verse 1]\nFootsteps echo louder now\nOn sidewalks meant for thousands\nStore windows dark and shuttered\nParking lots abandoned\nPlaygrounds wrapped in caution tape\nSwings moving in the breeze\nA world designed for people\nNow vacant as the sea\n\n[Pre-Chorus]\nNever thought I'd miss the noise\nThe hustle and the crowd\nNever knew that silence\nCould scream so damn loud\n\n[Chorus]\nEmpty streets where life once flowed\nEmpty streets, a world on hold\nSurreal as a movie set\nWaiting for the extras' call\nCities breathing quietly\nWhile we hide behind our walls\nEmpty streets remind us all\nOf what we took for granted\n\n[Verse 2]\nBirds reclaim the avenues\nWildlife ventures downtown\nThe world reset without us\nNature's soft rebound\nI walk my dog at midnight\nThe only soul for miles\nBeneath a clearer sky now\nWithout the constant din\n\n[Pre-Chorus]\nNever thought I'd miss the noise\nThe hustle and the crowd\nNever knew that silence\nCould scream so damn loud\n\n[Chorus]\nEmpty streets where life once flowed\nEmpty streets, a world on hold\nSurreal as a movie set\nWaiting for the extras' call\nCities breathing quietly\nWhile we hide behind our walls\nEmpty streets remind us all\nOf what we took for granted\n\n[Bridge]\nSomeday these streets will fill again\nWith laughter, honks and human scenes\nWe'll marvel at the photographs\nOf how the world once paused\nWill we remember lessons learned\nWhen crowds and noise return?\nOr rush back to forgetting\nHow precious simple gatherings\n\n[Chorus]\nEmpty streets where life once flowed\nEmpty streets, a world on hold\nSurreal as a movie set\nWaiting for the extras' call\nCities breathing quietly\nWhile we hide behind our walls\nEmpty streets remind us all\nOf what we took for granted\n\n[Outro]\nEmptiness with purpose\nSilence saving lives\nStrangest act of love we've shown\nStaying far apart"
        },
        {
            title: "Digital Connections",
            style: "Electronic indie pop with digital glitch elements, video call notification sounds, warm synthesizers beneath technological textures, connection-themed beats, and hopeful digital-age vocal processing",
            lyrics: "[Verse 1]\nGrandma learns to use a touchscreen\nSmiling through pixelated streams\nBirthday candles blown through cameras\nWeddings witnessed through our screens\nBook clubs meeting over wine now\nVirtual glasses raised up high\nEvery conversation starting with\n\"Can you hear me? Am I live?\"\n\n[Pre-Chorus]\nSeparated by necessity\nConnected by technology\nImperfect bridges spanning distance\nWhen physical touch is too risky\n\n[Chorus]\nDigital connections keeping us whole\nAcross the divide, reaching for souls\nFriendships sustained through fiber optic lines\nFaces in boxes, voices in time\nNever thought we'd treasure\nThese lagging conversations so much\nDigital connections, the closest thing to touch\n\n[Verse 2]\nQuiz nights, dance-offs, virtual choirs\nCreativity finds a way\nOffice meetings in our bedrooms\nPajama bottoms, business tops\nTeachers reaching through the ether\nTo students scattered far and wide\nChurches, temples, sacred spaces\nRebuilt in digital design\n\n[Pre-Chorus]\nSeparated by necessity\nConnected by technology\nImperfect bridges spanning distance\nWhen physical touch is too risky\n\n[Chorus]\nDigital connections keeping us whole\nAcross the divide, reaching for souls\nFriendships sustained through fiber optic lines\nFaces in boxes, voices in time\nNever thought we'd treasure\nThese lagging conversations so much\nDigital connections, the closest thing to touch\n\n[Bridge]\nPerhaps we never realized before\nHow precious it is to share our space\nWith those we love, those we need\nNow we grasp at digital reflections\nBetter than the silence of total separation\nGrateful for the tools that let us see\nEach other's smiles in real time\n\n[Chorus]\nDigital connections keeping us whole\nAcross the divide, reaching for souls\nFriendships sustained through fiber optic lines\nFaces in boxes, voices in time\nNever thought we'd treasure\nThese lagging conversations so much\nDigital connections, the closest thing to touch\n\n[Outro]\nThrough screens and cameras\nWe hold each other close\nNot the same but somehow\nEnough to help us through"
        },
        {
            title: "Cabin Fever",
            style: "Claustrophobic indie rock with manic energy, ticking clock motifs, restless percussion, walls-closing-in sound design, tense crescendos, and psychologically fraying instrumental sections",
            lyrics: "[Verse 1]\nDay fourteen or forty? I've lost count by now\nWalls that once held comfort start closing in somehow\nEvery creak and shadow magnified tenfold\nMy mind a busy highway with nowhere left to go\nCircling the living room, five steps there and back\nWatching paint imperfections, finding shapes in cracks\n\n[Pre-Chorus]\nThe clock ticks louder each day\nSame routines on repeat\nA psychological maze\nWith no exit I can see\n\n[Chorus]\nCabin fever, crawling up the walls\nCabin fever, bouncing off the halls\nStir crazy, mind hazy, patience worn thin\nSmall spaces, same faces, nowhere new to begin\nCabin fever, the prison of safety\nThe madness of sanity\n\n[Verse 2]\nBread baking, home projects, trying to stay sane\nExercise videos I follow in vain\nJigsaw puzzles, board games, streaming shows all day\nAnything to keep the creeping thoughts at bay\nTempers flaring over nothing, then apologies\nThe rhythm of confinement, our new normalcy\n\n[Pre-Chorus]\nThe clock ticks louder each day\nSame routines on repeat\nA psychological maze\nWith no exit I can see\n\n[Chorus]\nCabin fever, crawling up the walls\nCabin fever, bouncing off the halls\nStir crazy, mind hazy, patience worn thin\nSmall spaces, same faces, nowhere new to begin\nCabin fever, the prison of safety\nThe madness of sanity\n\n[Bridge]\nSometimes I just stand by the window\nWatching the world I can't touch\nDreaming of crowded restaurants\nAnd hugs I miss so much\nIs everyone feeling this fracture?\nThis slow-motion unraveling?\nThe paradox of being trapped\nIn the home we once called haven\n\n[Chorus]\nCabin fever, crawling up the walls\nCabin fever, bouncing off the halls\nStir crazy, mind hazy, patience worn thin\nSmall spaces, same faces, nowhere new to begin\nCabin fever, the prison of safety\nThe madness of sanity\n\n[Outro]\nTrying to remember\nThis isolation saves lives\nMakes the walls feel less like prison\nAnd more like sacrifice"
        },
        {
            title: "Essential",
            style: "Powerful heartland rock anthem with factory rhythm sections, honor-themed brass elements, working-class folk influences, heroic guitar solos, and grateful vocal delivery with community choir backing",
            lyrics: "[Verse 1]\nStocking shelves at midnight\nWhile the world's behind closed doors\nScrubbing down the hospital halls\nAs sirens call for more\nHarvesting the fields at dawn\nFood won't grow itself\nDriving trucks through empty streets\nTo keep the nation's health\n\n[Pre-Chorus]\nNever called heroes before\nInvisible until the world needed more\nThe backbone we took for granted\nNow the frontline of a war\n\n[Chorus]\nEssential, not expendable\nEssential, the foundation\nHands that heal, that build, that feed\nThat keep us all surviving\nEssential, undervalued\nEssential, now recognized\nWhen the world stopped cold in fear\nYou're the ones who carried us through\n\n[Verse 2]\nTeachers transforming living rooms\nTo classrooms overnight\nFactory workers masked and gloved\nProducing through their fright\nPackage carriers climbing stairs\nConnecting homes in need\nPharmacists counting pills\nSo healing can proceed\n\n[Pre-Chorus]\nNever called heroes before\nInvisible until the world needed more\nThe backbone we took for granted\nNow the frontline of a war\n\n[Chorus]\nEssential, not expendable\nEssential, the foundation\nHands that heal, that build, that feed\nThat keep us all surviving\nEssential, undervalued\nEssential, now recognized\nWhen the world stopped cold in fear\nYou're the ones who carried us through\n\n[Bridge]\nWill we remember after?\nWhen danger fades from view?\nWill we still see the value\nOf all that you still do?\nOr return to overlooking\nThe labor that sustains\nThe cashiers and the cleaners\nThe ones who remained\n\n[Chorus]\nEssential, not expendable\nEssential, the foundation\nHands that heal, that build, that feed\nThat keep us all surviving\nEssential, undervalued\nEssential, now recognized\nWhen the world stopped cold in fear\nYou're the ones who carried us through\n\n[Outro]\nThank you for your courage\nThank you for your care\nThank you for continuing\nWhen nothing felt fair"
        },
        {
            title: "New Normal",
            style: "Reflective alt-pop with adaptive rhythms, masked vocal effects, socially-distanced production elements, habit-forming percussion patterns, and resilient melodic themes despite restrictions",
            lyrics: "[Verse 1]\nMasks hanging by the doorway\nHand sanitizer in every bag\nElbow bumps instead of hugs now\nTwo meters kept between each tag\nRoutines we never imagined\nNow second nature to us all\nThe strange becoming familiar\nAs seasons rise and fall\n\n[Pre-Chorus]\nWe adapt because we must\nWe evolve because we can\nFinding ways to live and love\nWithin the constraints at hand\n\n[Chorus]\nNew normal, not what we chose\nNew normal, but here we go\nLearning to dance with restriction\nFinding joy despite condition\nNew normal tests our resilience\nNew normal reveals our brilliance\nDifferent doesn't mean broken\nJust means we keep on coping\n\n[Verse 2]\nBirthday drive-bys with honking horns\nWorkouts in living room corners\nZoom fatigue and outdoor dining\nPlastic barriers between borders\nCalculating risks with every plan\nIs this trip really worth taking?\nVaccination cards and test results\nNew rituals in the making\n\n[Pre-Chorus]\nWe adapt because we must\nWe evolve because we can\nFinding ways to live and love\nWithin the constraints at hand\n\n[Chorus]\nNew normal, not what we chose\nNew normal, but here we go\nLearning to dance with restriction\nFinding joy despite condition\nNew normal tests our resilience\nNew normal reveals our brilliance\nDifferent doesn't mean broken\nJust means we keep on coping\n\n[Bridge]\nPerhaps the strangest part of all\nIs how quickly strange became routine\nHow humans normalize the abnormal\nWhen survival demands we convene\nWith circumstances as they are\nNot as we wish them to be\nThe flexible survive and thrive\nWhile the rigid break and flee\n\n[Chorus]\nNew normal, not what we chose\nNew normal, but here we go\nLearning to dance with restriction\nFinding joy despite condition\nNew normal tests our resilience\nNew normal reveals our brilliance\nDifferent doesn't mean broken\nJust means we keep on coping\n\n[Outro]\nWondering what parts will remain\nWhen the danger fades away\nWhich habits formed in hardship\nWill actually be here to stay"
        },
        {
            title: "First Embrace",
            style: "Emotional cinematic indie folk, triumphant string arrangements, deeply human vocal performance, therapeutic release dynamics, celebratory reunion elements, and cathartic resolution themes",
            lyrics: "[Verse 1]\nTentative steps toward each other\nHesitation melts away\nArms extended, tears are falling\nFor this long-awaited day\nSkin on skin, warmth remembered\nWhat was once routine, now profound\nThe simple act of embracing\nNo longer taken for granted now\n\n[Pre-Chorus]\nAfter all the screens and distance\nAfter all the lonely nights\nAfter all the missed occasions\nAfter all the solo fights\n\n[Chorus]\nFirst embrace healing what words cannot touch\nFirst embrace worth every day we gave up\nHolding tight, making up for lost time\nPromising never to undervalue\nThe miracle of human connection\nFirst embrace after isolation\nTeaches us what matters most\n\n[Verse 2]\nGrandparents meeting newborn children\nFriends reuniting after loss\nLovers separated by borders\nFinally crossing what couldn't be crossed\nThe smell of someone's perfume\nThe texture of their favorite shirt\nAll the details screens couldn't capture\nWash over us in waves of worth\n\n[Pre-Chorus]\nAfter all the screens and distance\nAfter all the lonely nights\nAfter all the missed occasions\nAfter all the solo fights\n\n[Chorus]\nFirst embrace healing what words cannot touch\nFirst embrace worth every day we gave up\nHolding tight, making up for lost time\nPromising never to undervalue\nThe miracle of human connection\nFirst embrace after isolation\nTeaches us what matters most\n\n[Bridge]\nWe survived separated\nWe endured apart\nBut humans are made for contact\nFor sharing the same air\nFor standing in the same light\nFor healing through touch\nNo digital substitute\nFor arms wrapped around you\n\n[Chorus]\nFirst embrace healing what words cannot touch\nFirst embrace worth every day we gave up\nHolding tight, making up for lost time\nPromising never to undervalue\nThe miracle of human connection\nFirst embrace after isolation\nTeaches us what matters most\n\n[Outro]\nHold on a little longer\nMake up for time apart\nNever again forgetting\nWhat makes us who we are"
        }
    ]
};