// Define album data - making sure it's in the global (window) scope
window.pandemic_diaries_data = {
    folder: "Pandemic Diaries",
    name: "Pandemic Diaries",
    releaseDate: "2025-04-17",
    totalSongs: 7,
    coverArt: "asset/album-name/Pandemic Diaries/Art.jpg",
    songsData: [
        {
            title: "Day Zero",
            style: "Atmospheric alternative with news broadcast samples, tension-building percussion, anxiety-laden piano motifs, modern electronic elements, warning siren effects, and gradually mounting urgency",
            lyrics: "[Verse 1]\nHeadlines flash across the screen\nA distant threat now drawing near\nUncertainty begins to bloom\nIn hospital halls and living rooms\nWhile leaders debate how serious\n\n[Pre-Chorus]\nThe world holds its breath\nOn the edge of something unknown\nThe calm before the storm\n\n[Chorus]\nDay Zero, the moment before the fall\nDay Zero, when life seemed invincible\nThe invisible line between before and after\nThe last exhale of normalcy\nBefore the world stopped turning\n\n[Verse 2]\nShopping carts filled to the brim\nLast hugs given with nervous grins\n\"See you soon\" we said, not knowing when\nAirports closing one by one\nThe first lockdowns have just begun\n\n[Chorus]\nDay Zero, the moment before the fall\nDay Zero, when life seemed invincible\nThe invisible line between before and after\nThe last exhale of normalcy\nBefore the world stopped turning\n\n[Bridge]\nIn history books they'll mark this time\nWhen everything shifted in a blink\nThe last concert, the last movie\nBefore masks became armor for life\n\n[Chorus]\nDay Zero, the moment before the fall\nDay Zero, when life seemed invincible\nThe invisible line between before and after\nThe last exhale of normalcy\n\n[Outro]\nThe clock strikes midnight\nNothing will be the same again"
        },
        {
            title: "Empty Streets",
            style: "Hauntingly beautiful indie folk, sparse acoustic guitar, echoing percussion mimicking footsteps in vacant spaces, ambient urban silence recordings, and emotionally vulnerable vocals",
            lyrics: "[Verse 1]\nFootsteps echo louder now\nOn sidewalks meant for thousands\nStore windows dark and shuttered\nPlaygrounds wrapped in caution tape\nA world designed for people\nNow vacant as the sea\n\n[Pre-Chorus]\nNever thought I'd miss the noise\nThe hustle and the crowd\nNever knew that silence\nCould scream so loud\n\n[Chorus]\nEmpty streets where life once flowed\nEmpty streets, a world on hold\nSurreal as a movie set\nCities breathing quietly\nWhile we hide behind our walls\nEmpty streets remind us all\nOf what we took for granted\n\n[Verse 2]\nBirds reclaim the avenues\nThe world reset without us\nI walk my dog at midnight\nThe only soul for miles\nBeneath a clearer sky now\n\n[Chorus]\nEmpty streets where life once flowed\nEmpty streets, a world on hold\nSurreal as a movie set\nCities breathing quietly\nWhile we hide behind our walls\nEmpty streets remind us all\nOf what we took for granted\n\n[Bridge]\nSomeday these streets will fill again\nWith laughter and human scenes\nWill we remember lessons learned\nOr rush back to forgetting?\n\n[Outro]\nEmptiness with purpose\nSilence saving lives\nStrangest act of love we've shown\nStaying far apart"
        },
        {
            title: "Digital Connections",
            style: "Electronic indie pop with digital glitch elements, video call notification sounds, warm synthesizers beneath technological textures, connection-themed beats, and hopeful digital-age vocal processing",
            lyrics: "[Verse 1]\nGrandma learns to use a touchscreen\nBirthday candles blown through cameras\nWeddings witnessed through our screens\nEvery conversation starting with\n\"Can you hear me? Am I live?\"\n\n[Pre-Chorus]\nSeparated by necessity\nConnected by technology\nImperfect bridges spanning distance\n\n[Chorus]\nDigital connections keeping us whole\nAcross the divide, reaching for souls\nFaces in boxes, voices in time\nNever thought we'd treasure\nThese lagging conversations so much\nDigital connections, the closest thing to touch\n\n[Verse 2]\nQuiz nights, dance-offs, virtual choirs\nOffice meetings in our bedrooms\nTeachers reaching through the ether\nSacred spaces rebuilt digitally\n\n[Chorus]\nDigital connections keeping us whole\nAcross the divide, reaching for souls\nFaces in boxes, voices in time\nNever thought we'd treasure\nThese lagging conversations so much\nDigital connections, the closest thing to touch\n\n[Bridge]\nPerhaps we never realized before\nHow precious it is to share our space\nNow we grasp at digital reflections\nBetter than the silence of separation\n\n[Outro]\nThrough screens and cameras\nWe hold each other close\nNot the same but somehow\nEnough to help us through"
        },
        {
            title: "Cabin Fever",
            style: "Claustrophobic indie rock with manic energy, ticking clock motifs, restless percussion, walls-closing-in sound design, tense crescendos, and psychologically fraying instrumental sections",
            lyrics: "[Verse 1]\nDay fourteen or forty? I've lost count by now\nWalls that once held comfort start closing in somehow\nMy mind a busy highway with nowhere left to go\nCircling the living room, five steps there and back\n\n[Pre-Chorus]\nThe clock ticks louder each day\nSame routines on repeat\nA psychological maze\nWith no exit I can see\n\n[Chorus]\nCabin fever, crawling up the walls\nCabin fever, bouncing off the halls\nStir crazy, mind hazy, patience worn thin\nSmall spaces, same faces, nowhere new to begin\nCabin fever, the prison of safety\n\n[Verse 2]\nBread baking, home projects, trying to stay sane\nJigsaw puzzles, board games, streaming shows all day\nAnything to keep the creeping thoughts at bay\nThe rhythm of confinement, our new normalcy\n\n[Chorus]\nCabin fever, crawling up the walls\nCabin fever, bouncing off the halls\nStir crazy, mind hazy, patience worn thin\nSmall spaces, same faces, nowhere new to begin\nCabin fever, the prison of safety\n\n[Bridge]\nSometimes I just stand by the window\nWatching the world I can't touch\nDreaming of crowded restaurants\nThe paradox of being trapped\nIn the home we once called haven\n\n[Outro]\nThis isolation saves lives\nMakes the walls feel less like prison\nAnd more like sacrifice"
        },
        {
            title: "Essential",
            style: "Powerful heartland rock anthem with factory rhythm sections, honor-themed brass elements, working-class folk influences, heroic guitar solos, and grateful vocal delivery with community choir backing",
            lyrics: "[Verse 1]\nStocking shelves at midnight\nWhile the world's behind closed doors\nScrubbing down the hospital halls\nHarvesting the fields at dawn\nDriving trucks through empty streets\nTo keep the nation's health\n\n[Pre-Chorus]\nNever called heroes before\nInvisible until the world needed more\nThe backbone we took for granted\nNow the frontline of a war\n\n[Chorus]\nEssential, not expendable\nEssential, the foundation\nHands that heal, that build, that feed\nThat keep us all surviving\nEssential, now recognized\nWhen the world stopped cold in fear\nYou're the ones who carried us through\n\n[Verse 2]\nTeachers transforming living rooms\nFactory workers masked and gloved\nPackage carriers climbing stairs\nPharmacists counting pills\nSo healing can proceed\n\n[Chorus]\nEssential, not expendable\nEssential, the foundation\nHands that heal, that build, that feed\nThat keep us all surviving\nEssential, now recognized\nWhen the world stopped cold in fear\nYou're the ones who carried us through\n\n[Bridge]\nWill we remember after?\nWhen danger fades from view?\nOr return to overlooking\nThe labor that sustains\nThe ones who remained\n\n[Outro]\nThank you for your courage\nThank you for continuing\nWhen nothing felt fair"
        },
        {
            title: "New Normal",
            style: "Reflective alt-pop with adaptive rhythms, masked vocal effects, socially-distanced production elements, habit-forming percussion patterns, and resilient melodic themes despite restrictions",
            lyrics: "[Verse 1]\nMasks hanging by the doorway\nHand sanitizer in every bag\nElbow bumps instead of hugs now\nRoutines we never imagined\nNow second nature to us all\nThe strange becoming familiar\n\n[Pre-Chorus]\nWe adapt because we must\nWe evolve because we can\nFinding ways to live and love\nWithin the constraints at hand\n\n[Chorus]\nNew normal, not what we chose\nNew normal, but here we go\nLearning to dance with restriction\nFinding joy despite condition\nNew normal tests our resilience\nNew normal reveals our brilliance\nDifferent doesn't mean broken\n\n[Verse 2]\nBirthday drive-bys with honking horns\nZoom fatigue and outdoor dining\nCalculating risks with every plan\nVaccination cards and test results\nNew rituals in the making\n\n[Chorus]\nNew normal, not what we chose\nNew normal, but here we go\nLearning to dance with restriction\nFinding joy despite condition\nNew normal tests our resilience\nNew normal reveals our brilliance\nDifferent doesn't mean broken\n\n[Bridge]\nPerhaps the strangest part of all\nIs how quickly strange became routine\nHow humans normalize the abnormal\nThe flexible survive and thrive\nWhile the rigid break and flee\n\n[Outro]\nWondering what parts will remain\nWhen the danger fades away\nWhich habits formed in hardship\nWill actually be here to stay"
        },
        {
            title: "First Embrace",
            style: "Emotional cinematic indie folk, triumphant string arrangements, deeply human vocal performance, therapeutic release dynamics, celebratory reunion elements, and cathartic resolution themes",
            lyrics: "[Verse 1]\nTentative steps toward each other\nHesitation melts away\nArms extended, tears are falling\nFor this long-awaited day\nSkin on skin, warmth remembered\nWhat was once routine, now profound\n\n[Pre-Chorus]\nAfter all the screens and distance\nAfter all the lonely nights\nAfter all the missed occasions\n\n[Chorus]\nFirst embrace healing what words cannot touch\nFirst embrace worth every day we gave up\nHolding tight, making up for lost time\nThe miracle of human connection\nFirst embrace after isolation\nTeaches us what matters most\n\n[Verse 2]\nGrandparents meeting newborn children\nFriends reuniting after loss\nLovers separated by borders\nFinally crossing what couldn't be crossed\nAll the details screens couldn't capture\nWash over us in waves of worth\n\n[Chorus]\nFirst embrace healing what words cannot touch\nFirst embrace worth every day we gave up\nHolding tight, making up for lost time\nThe miracle of human connection\nFirst embrace after isolation\nTeaches us what matters most\n\n[Bridge]\nWe survived separated\nBut humans are made for contact\nFor sharing the same air\nFor healing through touch\nNo digital substitute\nFor arms wrapped around you\n\n[Outro]\nHold on a little longer\nNever again forgetting\nWhat makes us who we are"
        }
    ]
};